package-lock.json, package.json, src/plugins/vuetify.js, src/views/Login.vue
Used the icons from the existing package. Found them by searching in the link in #30. Resulting UI is the same.
Even though we may not use this login screen anymore (we will use the one from the hub :-). Fixing it just to remove the dependency size.
=> Fix issue #30 use only one material icon dependency

package-lock.json, package.json, src/model/User.model.js, src/services/suite.service.js, src/services/user.service.js, src/store/index.js, src/store/suites.module.js, src/store/user.module.js, src/utils/graphql.js, src/views/UserProfile.vue, tests/unit/model/user.spec.js, tests/unit/services/user.service.spec.js
For #38 
- Adds Sinon.JS for mocking
- Create a Suite Service refactoring the existing code in Vuex (which is good, Vuex has less one dependency)
- Create a User Service
- Adds a unit test for the User Service, that tests the Service, the Model, and Vuex. Only the layer for Axios (which does the HTTP query) is mocked.
This unit test should be used as example for future unit tests of services, as they will be pretty much the same. Mock the HTTP/GraphQL layer, and test the rest.
We still need to confirm Vuex will work fine once we have more tests. Can't say if they will run in parallel, or mess with the Store state.
Sending a pull request to see if Travis approves, and if - hopefully - the coverage goes up a bit 🎉
=> Add services

src/App.vue
Close #20 
Solution found [here](https://intellij-support.jetbrains.com/hc/en-us/community/posts/360000903779-vue-scss-file-cannot-resolve-) fixed the issue.
`npm run build` and the IDE automatic build are both happy now.
=> Fix alias warning in IDE

src/views/UserProfile.vue
Fixing linter error. Waiting on the set user = null before populating it now, to keep order of actions as expected.
=> Wait for set null before populating again

src/model/Suite.model.js, src/services/suite.service.js, src/views/Suites.vue, tests/unit/model/suite.model.spec.js, tests/unit/services/suite.service.spec.js
Close #71 
In the past during our first experiments with GraphQL, the endpoint was in `cylc/cylc-flow`. Now it resides in `cylc/cylc-uiserver`. The `cylc scan` was executed actually in a REST endpoint, that was executing the process locally in Python.
So this pull request removes the need to maintain that REST endpoint in `cylc-uiserver` (follow up PR after this one), and changes the Vue.js app to send a GraphQL query to the UI Server instead. The query used is:
```graphql
query {
tasks {
id, name, meanElapsedTime, namespace, depth
}
}
```
This change is based on the pull request by @dwsutherland to `cylc-uiserver`, which is [still pending review](https://github.com/cylc/cylc-uiserver/pull/34). And while I believe we may have code changes, the data model proposed by @dwsutherland has …
=> Use UI Server GraphQL endpoint for suites

src/components/core/Footer.vue
Display the application mode in the footer, when it is not equal to `PRODUCTION`. This is useful for troubleshooting and development.
I am planning to use a different response in the services in an mode (e.g. `offline`, for #75 and #77 ). This way we will be able to run the UI completely offline, with some mocked data. But also use other modes like `development` that could still point to development UI servers.
=> Show application mode in footer

src/components/core/Toolbar.vue, src/store/app.module.js, src/views/Suite.vue
Close #88 
Moves the View title from the Toolbar component data section to a global Vuex (`title` property of the `app` module).
The Suite view now works even after refreshing, and as the data is global, the Suite View is able to set the title to "Suite five", for instance.
Cheers
Bruno
=> Display view title even after refresh, and include suite name as example

src/model/Family.model.js, src/model/Task.model.js, src/services/mock/suite.service.js, src/services/suite.service.js, src/views/Suite.vue, src/views/Suites.vue, tests/unit/services/suite.service.spec.js, vue.config.js
Close #77 
The only important change for now in this PR is `vue.config.js`, which gets an __alias__ `suite-service`, used in JavaScript when importing the `SuiteService`.
When a developer specifies `NODE_ENV=?`, that value will be used, and if the value is equal to `offline`, then the returned value will be `@/services/mock/suite.service`. Otherwise it will use the real service `@/services/suite.service`, that instead of using the mocked data, it will pull from the GraphQL endpoint.
Other changes here include some new classes that will be used in #78 , with some changes to accommodate the required data structure of the Vue.js component used to render the tree view.
=> Introduce mode offline with mocked data for testing/development

tests/unit/graph/graph.spec.js
Fix unit tests by avoiding timeouts in tests by mounting the component just once.
There are warnings about canvas not available, but the tests are passing locally. I think we will need to review the tests later.
Feel free to merge if the build is passing on Travis :+1:
=> Mount component once at test, avoiding timeouts

src/services/suite.service.js
Hi,
I had written a transformer for the component we are using for the suite tree view, vue-ads-table-tree. But I used it only in the mocked data, when running the system in offline mode (i.e. `NODE_ENV=offline`).
Luckily, simply applying the transformer in the service with the real data seems to fix the current suite tree view, allowing others to see the tasks being updated in short intervals (we are polling the data in 3 seconds I believe).
@hjoliver let me know if this one works for you too, please.
Cheers
Bruno
=> Run data returned from GraphQL through vue-ads-table-tree transformer

src/components/cylc/Job.vue, src/components/cylc/Task.vue
close #100 
Add components for the task an job status icons.
* One component for tasks and one for jobs, respond to state changes ala Vue.
* `inline-block` level components `1em x 1em` which can sit in text without disrupting the baseline (much).
I'm not sure how best to incorporate these components into a Vue view. We want these components to feed off of the data model of the component which uses them, are `props` good enough for this?
For the moment these are standalone components.
```vue
<template>
<span>
<Task />
foo
<Job />
</span>
</template>
```
Fiddling the `data` in the components you will get something like this:
* Incorporate into views.
* Work out how we are going to feed data into these components (e.g. props or whatever).
* Animate state changes.
* Pure CSS probably wont be …
=> Task job icons

tests/unit/services/suite.service.spec.js
I broke the build when fixing #105 as I applied the transformer to the GraphQL data. The unit test then instead of simply getting the data returned as-is, it started getting the data after the transformation.
So just updated the test to match the returned data. This should increase the coverage a bit, but that's not really relevant. As the component will change, as well as layout :+1:
=> Fix unit test after applying transformer

src/views/Suites.vue
Closes #104 
The suites view displays a table with the suites (workflows). When the page is being loaded, there is a loading indicator at the very top of the page (before it's loaded, you should see a quick bar at the top).
Then, once loaded, there is another asynchronous task to retrieve the list of suites (calling the `SuiteService.getSuites`). That task is using Axios, and we have a [global interceptor](https://github.com/cylc/cylc-ui/blob/78f802e5713f6b33bb904f91a5cd4eb9ed4eb445/src/plugins/axios.js#L7) in Axios to set a global flag `isLoading` to `true` whenever there is a request in action.
The table of suites is a component from Vuetify, that [supports a loading indicator](https://vuetifyjs.com/en/components/data-tables#api). The loading indicator was attached to the global …
=> Use a local isLoading flag for the suites view table

src/components/cylc/Job.vue, src/components/cylc/Task.vue
Addresses https://github.com/cylc/cylc-ui/pull/101#issuecomment-508957544
* Namespace the task and job CSS components.
* Set default data values to `null` (rather than example values as before).
This PR follows the convention of Vuetify of `c-$class_name`.
=> taskjob: namespace css

src/components/cylc/Task.vue
The Task scss file is missing a dot in the class name (the Job one looks OK). Resulting in a much larger than expected icon.
=> Add missing dot for class name

src/router/paths.js
Spotted by @sadielbartholomew, no reason to have Graph with an alias to /
=> Remove alias to / from the Graph view

src/components/core/Alert.vue, src/router/index.js, src/services/suite.service.js, src/services/user.service.js, src/store/index.js, src/views/Suites.vue, tests/unit/services/suite.service.spec.js, tests/unit/services/user.service.spec.js, tests/unit/store/store.spec.js
Instead of accumulating the error messages in a list, after this PR we will have just one alert. If, for any reason, the alert changes (e.g. you get a "Network error", and then something causes a "Unknown error"), then the latest message will be displayed.
Users can still dismiss the error. And when moving to a different route, it should be correctly removed, and no more alert/error should be displayed in the new page/view.
=> Display single error message

src/components/cylc/Toolbar.vue, src/layouts/Default.vue, src/router/index.js, src/styles/cylc/_toolbar.scss, src/styles/index.scss, src/styles/material-dashboard/_variables.scss, src/views/Suite.vue
Closes #114 
Adds initial version of our new toolbar. This toolbar component is actually based on Vuetify's [toolbar](https://vuetifyjs.com/en/components/toolbars).
With the difference that it 
- overrides a few CSS styles
- has extra CSS styles
- has extra control over the extended feature
Icons are using material design icons, and typography and layout & spacing are also material's default, hence a few differences if you look closely and compare with @oliver-sanders ' sketches.
=> Create view control toolbar

src/components/cylc/Header.vue
Close #148 
@oliver-sanders apparently just needed to specify the width and height. Also copied extra attribute from the [StackOverflow answer](https://stackoverflow.com/a/37074597) where I found the fix.
Firefox 68.0.1:
Chrome 75.0.3770.142 (with adblock on, and cropped a piece of the logo to the left because of my bad skills with screenshots, but it's displaying just like in Ffox):
One review should do?
=> Fix logo chrome

src/components/cylc/Header.vue
I think Inkscape must have inserted this `openswatchbook` nonsense. The `:osb` namespace isn't used in this document so the definition isn't needed, also http://www.openswatchbook.org gives a 503 so it definitely isn't doing anything (except potentially causing an extra request).
=> remove osb domain from svg

src/components/core/Drawer.vue, src/router/paths.js, src/styles/cylc/_variables.scss, src/styles/index.scss
Replaces the green colour by the colour defined in the sketches PDF.
Also removes the alias for dashboard, this way we have a single link and the active menu works when you load the landing page.
=> Set menu active colour, and remove dashboard alias

src/components/core/Drawer.vue, src/components/core/Footer.vue, src/components/cylc/Toolbar.vue, src/lang/en-GB/App.json, src/lang/en-GB/NotFound.json, src/lang/en-GB/Toolbar.json, src/lang/en-GB/UserProfile.json, src/lang/en-GB/Workflows.json, src/lang/pt-BR/App.json, src/lang/pt-BR/NotFound.json, src/lang/pt-BR/Toolbar.json, src/lang/pt-BR/UserProfile.json, src/lang/pt-BR/Workflows.json, src/mixins/index.js, src/router/paths.js, src/views/Dashboard.vue, src/views/GScan.vue, src/views/Graph.vue, src/views/NotFound.vue, src/views/Tree.vue, src/views/UserProfile.vue
Adds new i18n translations, and updates the ones that have been removed.
This also closes #142 , as the application name (Cylc UI) is now centralized in the i18n messages files. This allows to reuse it for Footer, and also for the page titles.
=> Update i18n or add when missing

src/components/core/Drawer.vue, src/views/Dashboard.vue
Part of #94, opening the way for #139. This pull request removes all the links from the sidebar, but the Suites/Graph view links.
The idea is that this way, once GScan works begin, the other links such as Hub, User, etc have already been moved elsewhere (the login page was done in #147).
Tried to follow the example from the current design document (#87 ), but my SvgFu fails me @oliver-sanders . Do you reckon it would be easy to create the arrows and connect the nodes, as in the sketch?
I used the components `Task` and `Job` and the result is close to the sketch. There is some example code in this PR with the ID of the `Task` element, which contains the SVG node.
Then, there is a JS function pending implementation where I was going to start working on creating the lines/arrows.
The issue …
=> Update landing page / dashboard

src/components/cylc/Task.vue
@oliver-sanders I think the progress in the tasks has been broken for a while. I noticed it while reviewing your PR #168 
If you look at your example code, you have progress set to `0.3`. The code seems to be expecting `30`. But even passing `30`, I didn't get anything in Chrome or Firefox.
After removing the extra `+` sign, it worked on chrome. But on Firefox it did not work. I tested replacing the `calc(157 - (157 * ${this.progress / 100} + ))` (which was working on Chrome) by simply `109.9`, and it worked.
Undoing this change, and going back to the Firefox browser console, it is possible to see that Firefox rejected the value expression for `stroke-dashoffset` (there is a warning in the CSS category, which is not always enabled for me).
In this PR, I've moved the calculation logic to …
=> Fix Task progress

src/components/core/Footer.vue, src/store/index.js, src/store/user.module.js, src/store/workflows.module.js, tests/unit/services/user.service.spec.js, vue.config.js
Remove the [getters](https://vuex.vuejs.org/guide/getters.html) from Vuex stores. The getters are similar to `computed` values in Vuejs.
So you will only need them when you have a value that depends on some `state` data from Vuex, using reactivity. This will eliminate unused code, and make it easier to write the unit tests.
This closes #122
=> Remove (unnecessary) vuex getters

src/components/cylc/Task.vue
Companion to https://github.com/cylc/cylc-flow/pull/3230
Add a held icon to the task state.
For the moment I've kept the task icon square (which is much simpler). We may want to change this later, perhaps make the task icon a little wider and budge the held icon to the left a bit.
Will leave this as is for now until we have decided what we are doing with the retry state.
```vue
<template>
<div>
<ul v-for="state in states">
<li>
<task
:status="state"
:isHeld="false"
/>
<span style="padding-left:0.5em"></span>
<task
:status="state"
:isHeld="true"
progress="0.3"
/>
foo
<job :status="state" />
</li>
</ul>
</div>
</template>
<script>
import Task from '@/components/cylc/Task'
import Job from '@/components/cylc/Job'
export default {
components: {
task: Task,
job: Job
},
data: () => ({
states: [ …
```
=> task: add isHeld attribute

src/components/cylc/Task.vue
Proposal to close #173 (because it's faster to code than draw for this one)
* Visually clarify that succeeded and failed are both "completed" states.
* Visually distinguish failed from submit-failed
* Remove hub (circle) from submit-failed icon (because it's just messy)
Idea credit @hjoliver
=> Task failed

src/components/core/Drawer.vue, src/styles/cylc/_sidebar.scss, src/styles/cylc/_toolbar.scss
Closes #193 
@hjoliver here's a preview
(strange dark thin border at the bottom is the XFCE menu, not part of the UI)
=> Remove border from: Header, Sidebar, and use floating style for NavDrawer

src/views/Dashboard.vue
Had noticed some days ago that the `Dashboard.vue` when displayed always resulted in some console errors.
```
Error in mounted hook: "TypeError: Cannot read property 'children' of null"
```
This was due to some function I left from the initial implementation, when I was working on that graph-like display, with connected dots.
We decided not to add that for now, but I forgot to remote the functions. Sorry.
One review should be enough, as this code is not used.
=> Remove unused functions in Dashboard.vue

package-lock.json
Fix for the two recent security alerts. It actually reported fixing 4 issues.
```
updated 1 package in 14.168s
fixed 4 of 6 vulnerabilities in 39146 scanned packages
2 vulnerabilities required manual review and could not be updated
```
The other two are known vulnerabilities without immediate fix #132 
```
=== npm audit security report ===                        
┌──────────────────────────────────────────────────────────────────────────────┐
│                                Manual Review                                 │
│            Some vulnerabilities require your attention to resolve            │
│                                                                              │
│         Visit https://go.npm.me/audit-guide for additional guidance          │ …
```
=> Fix security vulnerabilities after GitHub alert

src/components/core/Drawer.vue, src/router/paths.js
Fix browser console warning (yellow-ish console log, not really an Error and frequently ignored) for "[vue-router] Duplicate named routes definition: { name: "Dashboard", path: "" }".
I probably accidentally added a duplicate route while adding the Dashboard view I guess. Trivial change (click on the blue icon in the diff near the top of the change to see more of the file, and keep doing that until you can see another route that is also mapped to `Dashboard` view), one review should do :+1:
=> Remove duplicate Dashboard route

src/services/gquery.js
Closes #213 
This PR uses `process.env.NODE_ENV`, which contains the Vue.js application mode. Most of the time I am working with the `offline` mode, which is a custom mode we created.
But users will run on the `production` (except for `offline`, all other names here are standard names in Node.js/Vue/etc). Developers by default run on `development`, unless they specify `offline` or another mode.
The value of `process.env.NODE_ENV` gets replaced by the string value during compile-time by... WebPack I guess.
The solution on this PR checks that value - which is common practice - and when it is set to something different than `production`, it will log the query, but now to `debug` level (`console.error` goes to error logging level, `console.warn` to warn logging level, and so it goes).
So …
=> Log GraphQL queries to debug level only

src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, src/services/mock/generate, src/views/Tree.vue
The issue with `generate` and mock data was in my environment (see #192 and thanks @matthewrmshin !). Once fixed, managed to re-run the script using `master` from both Cylc UI Server and Cylc Flow, and update the mock data.
Also updated `Tree.vue`'s GraphQL query, and tested with offline mode, and with real data.
Part of #145 , just submitting before as it will take a bit more to finish that component's PR, and it will make it easier reviewing the PR.
Also closes #191 
Cheers
Bruno
=> Add host and progress information (mean elapsed time, execution time) to GraphQL query (mock and real)

src/components/cylc/TreeItem.vue, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, src/services/mock/generate, src/store/workflows.module.js, src/views/Tree.vue, tests/unit/store/workflow.store.spec.js
Closes #220 
Implemented and with tests, but I am not sure if it is working or not :confused: 
For my workflow `five`, modified to run `script = sleep 2` for every task, and with a more distant stop point, it only displays progress as 0% or 100%.
I had a look at the code, and also at the response of the GraphQL queries... if I configured the script command to sleep for 2 seconds, the `meanElapsedTime` returned always 2 seconds.
Using that number with the old code ported to JS (using the job `startedTime` and the `Date.now()` time in JS), it looked to me like it had to always return 0 or 100 indeed.
Later, I changed the script to be: `script = "sleep $[ ( $RANDOM % 30 )  + 1 ]s`, in the hope the `meanElapsedTime` would be different. It was, at one point I was getting `12.4...`. But even …
=> Add function to compute percent progress for the Tree component

src/services/mock/checkpoint.js
Quick PR that does not change any source code, only a file that is generated by the `generate` script. Reason for this, is that the part of the query to order cycle points was not working (see #238).
Re-generated the mock data with the PR prepared by @dwsutherland (thanks!). This is useful only for screenshots and for future work, to make sure we don't confuse users - or ourselves with incorrectly ordered cycle points :)
Another 1 review issue IMO
Cheers
Bruno
=> Order jobs per cycle point in mocked data

package-lock.json, package.json, src/plugins/flags.js, src/plugins/index.js
Closes #211 
One review should do it IMO. I was the one who added it, for the old drop down language switcher. We don't have that component now, so this shouldn't break anything.
Tested locally, no console errors or other errors.
Cheers
Bruno
=> Remove vue-flag-icon dependency

src/components/cylc/Tree.vue, src/components/cylc/TreeItem.vue, src/store/workflows.module.js, src/views/Tree.vue
Part of #222 
Not sure if will be done before 0.1, but it is part of the problem in the memory performance issue.
The three caches were holding references to objects that were never removed or collected. Found by filtering for detached in the Chrome memory tool, then expanding the nodes until I located several that were retained due to the caches.
(doesn't actually show the cache, but was around there where I located the issue)
It appears - after some initial test post midnight, so to be reviewed tomorrow morning - to fix the issue. However, still need to:
=> Fix cached items retained after Tree component is destroyed

src/views/GScan.vue
Reported by @hjoliver on Riot, but he mentioned @oliver-sanders was the one that spotted it
> (...)  have noticed one more problem. With two suites running, in the workflow list they now appear on the same line.
The image attached
Successfully reproduced locally
Then confirmed that it was during the Vuetify migration. I missed adding a `<tr>`, so instead of having to rows (table row = tr), we get only a bunch of columns piled up together.
Quick fix, here's the end result
=> Add tr to table row in Workflows/GScan view

src/components/material/Card.vue, src/lang/en-GB/Workflows.json, src/lang/pt-BR/Workflows.json, src/views/GScan.vue
From Riot today, @hjoliver 
> (...) the text in the grey box is a bit verbose and repetitive.  And the information is also redundant given the blue heading up top.
> (...)
> For the moment let's just make the existing text more concise.  i.e. "Your Workflows"
This PR changes the title text to "Your Workflows", removes the subtitle (text below it), and adjust margins after the change.
Here's before: 
Here's the end result:
Assigning @hjoliver to review as he requested the change. I think 1 review is enough, but otherwise anyone can feel free to jump in and have a second look at the change :+1:
=> Use only Workflows table title

src/components/cylc/Tree.vue, src/components/cylc/TreeItem.vue, src/store/workflows.module.js, tests/unit/components/cylc/tree.data.js, tests/unit/components/cylc/treeitem.vue.spec.js
Closes #247 
Set to 0.2, so no need to merge/review now :+1: 
Changed instead of `expanded` in `TreeItem`, now it is `initialExpanded`, which denotes that that is only the initial state.
Then `beforeMount` is used to set the state to whatever was defined in the Vuex store. Meaning that before mounting the node in the DOM it will check if there is a desired `expanded` state in the data. If not, it will go with the `initialExpanded` :+1:
=> Hide jobs by default in the Tree View

src/services/gquery.js
Small improvement for the `gquery` `print` function.
Noticed it the other day while working on some issues, and added a post-it so I wouldn't forget it.
When the mode is production, the function is currently doing some string manipulation, just to reach the end of the code and decide it won't print as it is production.
A better approach, IMO, is to just return immediately if production :+1:
=> Avoid any calculation in print function when in production

.nycrc, vue.config.js
Closes #255 
Had to play with the settings a bit. First commit is re-enabling the coverage. Next commit is to match that istanbul plugin documentation, making it easier to check for differences. Then we reformat the JSON in the next commit, and finally had to enable `instrument` and `sourceMap`, as otherwise it would report only on covered file (i.e. exclude not covered files, giving a coverage report number of ~94%).
=> Fix coverage

tests/unit/services/gquery.spec.js
Started working on #234 today, which I thought would be a 30 minutes job. But then got stuck trying to add the variables to the query, and noticed I was changing a lot of code in `gquery.js`.
I realized it didn't have unit tests yet, so started adding a few ones here. Will add a few more tomorrow, but I digressed a little today (2 hours) trying to get the coverage to work (#255) with no luck.
=> Add unit tests for GQuery

CONTRIBUTING.md, src/services/gquery.js, vue.config.js
Fixes #271
Ran unit tests, and both `build` and `build:report` - everything seemed fine (except for some `console` usages reported by eslint).
=> Replaces usages of `var` with `const`

src/components/cylc/Toolbar.vue, src/layouts/Default.vue, src/views/Tree.vue
Closes #253 
At the moment the toolbar is displayed all over the pages/views in Cylc UI. But the design ketches actually hid it, and displayed it only on the pages with workflows running.
This PR
- Moves the toolbar to within the Tree view (this would have to be replicated in the Graph view for now, but in the future we will have a single view with tabs)
- Removes the elements that were used to display where/how things would be, adding `TODO`'s
If the second part of the PR is fine, I will add issues set to the 1.0 milestone. I left the pause and stop buttons, as I think we are ready to add these. I believe @dwsutherland has created the mutations already. All that is missing is investigate what is missing in the UI to call that. So this should be fixed soon for 0.2.
But if others prefer, …
=> Display toolbar for workflows only

CONTRIBUTING.md, src/views/Dashboard.vue
Remove `row` prop from `<v-layout>` to align hover with sibling elements and maximise use of space.
Closes #270
=> Fix size of dashboard links on hover

CHANGES.md, src/router/index.js, src/services/mock/user.service.mock.js, src/services/user.service.js, src/views/UserProfile.vue, vue.config.js
Closes #260 
This PR first adds a mock service for the `UserService`. The returned information should be the same for everybody, with the exception of created date, which is a `new Date()` object, meaning it will display different whenever called.
So now this view should work on the offline mode.
Then we move the call to the `/userprofile` service from the `UserProfile.vue` view to a global route guard.
This guard will check if the Vuex store contains a user already in place. If not, it will fetch the user information from JupyterHub, and store in the Vuex store.
After this, the application should have the `store.state.user.user` information available to any screen/module/code/etc that may need it, e.g. #258 
Cheers
Bruno
=> Load user information on application startup

CHANGES.md, src/components/cylc/Tree.vue, src/components/cylc/TreeItem.vue, src/components/cylc/tree/event-bus.js, src/views/Tree.vue
Part of #222 and #227 
The first commit was cherry-picked from the #251 PR. This commit removes code that was `watch`'ing a data structure and clearing all caches. Now it listens to only one event for when the node is deleted, and then removes that treeitem from the cache.
Confirmed in the Vue Dev Tools browser extension that the cache was being updated correctly.
The second commit is the reason for this PR being WIP. I noticed we had a lot of `closure` object in the heap. And even some events in the detached state.
My guess was that a) using closures like `@on:click='$emit(...)'` was triggering the events too soon, or maybe invoking the events for parents too, and b) having to propagate the event back to parents wasn't efficient.
Now we have a global event bus for the tree component, …
=> Keep cache in sync, and use a global event bus

.nycrc, vue.config.js
After this PR, our code coverage on Codecov will include both `.js` and `.vue` files. The coverage will decrease, but that's better than not seeing how much of `.vue` single file components are being tested :+1: 
Before: https://codecov.io/gh/kinow/cylc-ui/tree/master/src
After: https://codecov.io/gh/kinow/cylc-ui/tree/include-vue-coverage/src
=> Include .vue components in coverage report

src/router/index.js
It is possible that the `user` object will be accessed from the Vuex store while the `Promise` has not yet been fulfilled. This PR just changes the logic to call `next()` only if we already have a user, or after the `Promise` has completed.
=> Prevent accessing user when still undefined

src/services/mock/user.service.mock.js, src/views/UserProfile.vue
Noticed after rebasing the issue that I had a bug in my `Promise`. Was returning a `Promise` that returned a `Promise` (Vuex store method), instead of chaining it. But I think we also don't need to chain anything, instead we can just simply return the Vuex method/`Promise`.
But that showed that there was a bug (probably old) where the username was not displayed in the form. Probably nobody noticed because we rarely need that screen.
=> Fix promise use in mocked data, and field being displayed in user form

src/components/cylc/Task.vue, src/components/cylc/Toolbar.vue, src/services/gquery.js
Simply prevents build warnings for calls to methods of `console`. The exceptions added are already protected by `if (process.env.NODE_ENV !== 'production') {` - meaning print only when not production environment - or are intentional - like in `Task.vue`.
=> Ignore no-console eslint rule in a few places

src/router/index.js, src/router/paths.js, src/views/Tree.vue
These changes close #293
Simply accept the complete `path` object, modifying it to use the `view` value when `name` is missing (i.e. keeping previous behaviour).
This allows the approach used by @MartinRyan in the Graph component PR to work, of [passing props to route components](https://router.vuejs.org/guide/essentials/passing-props.html). Easier than relying on the route parameters directly. Vue Router instead will inject the param to the view.
What happened in the Graph PR was that even though Martin added `props: true`, it was ignored as it was not expected by the function. The code now will use whatever we define in `paths.js`.
=> Support any attributes defined in paths.js when creating routes

src/components/cylc/Task.vue
close #201
The renaming of the ready/queued state(s) will have to come in a future PR after the change is made to Cylc Flow.
=> add preparing icon

src/views/Dashboard.vue
Minor dashboard tweak - the new responsive web site doesn't like "documentation.html".
One review will do!
=> Cylc doc URL fix.

src/components/cylc/Job.vue, src/styles/cylc/_job.scss, src/styles/index.scss
Address theme component of #109.
Add theme support for Job icons:
* Normal
* Colour-blind
* Greyscale
These respond to the `job_theme--<name>` class of a containing element intended to match the application `theme--<name>` class.
At present we don't have a way to toggle themes or for storing user preferences.
i.e. `App.vue`.
```vue
<template>
<v-app>
<div v-for="theme in themes" :class="['job_theme--' + theme]">
<h2>{{theme}}</h2>
<ul v-for="state in states">
<li>
<task :status="state" progress="0" />
foo
<job :status="state" />
</li>
</ul>
</div>
</v-app>
</template>
<script>
const defaultLayout = 'empty'
import Task from '@/components/cylc/Task'
import Job from '@/components/cylc/Job'
export default {
computed: {
layout () {
return (this.$route.meta.layout || defaultLayout) + '-layout' …
```
=> theme: job icons

package-lock.json, src/components/cylc/Graph.vue, src/styles/cytoscape/cytoscape-custom.scss, src/styles/cytoscape/html-label.scss
Tidy up graph view styling, to at least make it more clean looking (if not actually conforming to our design at this stage, due to unresolved issues).
- use our job icon colours (mostly/sort-of) for graph nodes, and repeat some colours to approximate our new set of statuses better
- remove the gray "donut" shapes etc. inside each node (not sure what those were for, but they didn't look good ... maybe some experiment to approximate job progress or something in lieu of our svg task icons?)
- slightly less horrible font in the pop-ups
- also stops the animation from scratch on every update, for the other layouts, which is no good for a live monitor view (however, it still does a single double-jump for reasons that I couldn't figure out in the time available).
=> Graph View style tweaks.

src/components/cylc/gscan/index.js
@hjoliver related to the discussion on Riot about the job status "ready". Due to #310 you may have to move your mouse over the area of the icons to confirm there is no tooltip for "ready" 😄 the first icon that should display the tooltip is "running" (in alphabetical order, unless you have some failed or some other < "ready").
=> Skip the job status "ready" until the backend is updated

src/components/cylc/Job.vue
These changes close #310 
This change appears to solve the transparent/missing job icons for now.
=> Add a span parent to the job component to specify the theme (normal by default)

src/components/cylc/Task.vue
Get rid of the remaining `?` undefined task state icon that regular appears in the tree view.  The old "ready" status, still coming from the back-end, is to be renamed "preparing" - but we can use the new "open small dot" icon for it already. :+1:
=> Show ready/preparing task status.

.github/workflows/main.yml
Noticed that after marking a PR as ready for review it was not showing that the GItHub action had run successfully. Then found [a similar issue](https://github.com/sdras/awesome-actions/issues/98) (that repository has a lot of useful things for actions), and turns out I also did not include the `on: [pull_request]`, only `on: [push]`.
EDIT: added an extra commit to fix the coverage reports. Will have to add a secret token to the repo settings too, as documented in the Codecov github action docs: https://github.com/codecov/codecov-action
One review should to :+1: 
=> Execute GitHub action on pull requests too and fix coverage

CHANGES.md, src/components/cylc/Graph.vue, src/components/cylc/Toolbar.vue, src/layouts/Default.vue, src/router/index.js, src/router/paths.js, src/store/workflows.module.js, src/views/GScan.vue, src/views/Graph.vue, src/views/Tree.vue, tests/unit/components/cylc/toolbar.vue.spec.js
These changes close #199 
Moved `Toolbar` component back to the `Default` layout, making it dependent on Vuex store `workflows.workflow` state, instead of `props`.
The components `Tree`, `Graph`, 
=> Fix toolbar (responsive mode and drawer)

public/img/logo.svg
The XML namespace was missing from the `<svg />` tag which could cause browsers to refuse rendering in certain circumstances. E.G. try viewing the SVG file directly in your browser.
=> logo: add svg xml-namespace

src/components/cylc/Task.vue, src/styles/cylc/_task.scss, src/views/Guide.vue
Closes the "eccentric task states" component of #109
Proposal to handle the expired state:
* ~Mark "expired" tasks as "succeeded", this is how they are handled in the graph.~
* ~Most the time they should be easily distinguished from naturally succeeded tasks by the absence of a job.~
* Treat "expired" as a top-level status with its own icon.
Questions:
Screenshot:
=> task: support expired state

CHANGES.md, package-lock.json, package.json, src/components/core/Footer.vue, src/components/cylc/Graph.vue, src/components/cylc/Toolbar.vue, src/components/cylc/TreeItem.vue, src/components/cylc/workflow/Workflow.vue, src/components/cylc/workflow/index.js, src/main.js, src/router/paths.js, src/services/gquery.js, src/services/workflow.service.js, src/store/workflows.module.js, src/styles/cylc/_footer.scss, src/styles/cylc/_workflow.scss, src/styles/index.scss, src/views/Graph.vue, src/views/Workflow.vue, tests/unit/components/cylc/toolbar.vue.spec.js, tests/unit/components/cylc/workflow/workflow.vue.spec.js, vue.config.js
These changes close #90, and close #323 
=> Create Workflow component with Lumino

src/views/Workflow.vue
=> Add a tree component by default when accessing the workflow page

package-lock.json, package.json, src/components/cylc/Graph.vue, src/styles/cytoscape/cytoscape-custom.scss
Some graph view changes for the alpha-2 release:
- delete the 3 useless layouts
- delete the expand/collapse code
- fix the cytoscape errors spewed to the console
- improve the buttons a bit (highlight the chosen layout, and the freeze button when frozen)
=> Graph view cleanup

src/styles/cylc/_workflow.scss
Address comments (somewhere) on unused space at the bottom of the workflows component.  It was still sized as if the old footer existed.
Also shrunk the minimum tab size a bit.
=> Tweak workflows component sizes.

src/components/graphqlFormGenerator/FormGenerator.vue, src/components/graphqlFormGenerator/FormInput.vue, src/components/graphqlFormGenerator/components/FormInput.vue, src/components/graphqlFormGenerator/components/List.vue, src/components/graphqlFormGenerator/components/NonNull.vue, src/components/graphqlFormGenerator/mixins.js, src/router/paths.js, src/views/Mutations.vue, tests/unit/components/graphqlFormGenerator/formgenerator.vue.spec.js
Addresses the first three points of #339 
This PR adds a temporary "mutations" view which lists available mutations and auto-generates forms for them on request.
This is orthogonal to https://github.com/cylc/cylc-flow/pull/3469 which makes the mutations more declarative and brings them more inline with the Cylc CLI.
Getting the nested components and data model working correctly took nearly all the time. Thanks for the `<component :is="class" />` suggestion @kinow, I would have wasted days otherwise :+1:.
**Overview:**
* Introspect the GraphQL schema for information about mutations.
* Auto-generate forms to act as interfaces to these mutations.
* When complete output JSON from these forms to be used as arguments in the GraphQL request.
**Caveats:**
* ~Some of the default values in the …
=> api on the fly - part 1 - generate forms from mutations

CHANGES.md, src/components/cylc/Drawer.vue, src/lang/en-GB/Workflows.json, src/lang/pt-BR/Workflows.json, src/views/Dashboard.vue, src/views/GScan.vue
The old "gscan table view" is not part of our UI design plans, is now somewhat redundant with the new gscan side-bar (and the Actions links in it are broken since lumino,and not needed since gscan side-bar).
However, we **may** want to keep it as a convenient way to show workflow-level detail that users normally don't need to care about (host, port, etc.) ... at least until we figure out if the same info can be dropped from UI or incorporated un-intrusively into the side-bar (e.g. - offline chat with @oliver-sanders - we could optionally put host as a top level tree item).
For the moment, this fixes up the table and hides it away a bit, in the Dashboard:
- remove the Actions column
- make rows clickable (with same result as clicking on the …
=> Workflows table tidy and hide

public/index.html
Quick question, should we be setting the `X-UA-Compatible` flag?
Probably no harm done, Vuetify apparently [supports IE11 via pollyfill](https://vuetifyjs.com/en/getting-started/browser-support).
=> drop IE support?

src/views/Dashboard.vue
These changes partially address #362 
Found while debugging the websockets connections. The queries must be sent as subscriptions, otherwise the client may use the HTTP link instead.
=> Use subscription instead of normal query in the Dashboard view

src/components/cylc/Drawer.vue
These changes close #369 
A possible fix for #369, adding the old version&node env string to the GScan footer. This could be moved under the logo if it looks better. I moved under the `Drawer` items, as the Vuetify component already offers an "append" slot, that they also use for their documentation. But happy to amend this change if necessary :+1: 
Leaving as 0.3, same milestone as #369.
=> Use the Drawer component "append" slot from Vuetify to append a version string, as in their documentation page

src/components/graphqlFormGenerator/FormInput.vue, src/views/Mutations.vue, tests/unit/components/graphqlFormGenerator/mutations.vue.spec.js
Addresses the fourth point of #339 
~**Note - Built on top of #357**~ now merged
**Note - Works with the data types defined in https://github.com/cylc/cylc-flow/pull/3469**
Use the argument types defined in the GraphQL schema to associate mutations with "Cylc Objects" by which I mean workflows, cycle point, tasks, etc.
This mapping will be used when you right-click on something (say a task in the tree view) to work out which mutations are relevant to the thing you clicked on.
At the moment this is built into the temporary Mutations view.
**Example**
**TODO**
=> api-on-the-fly - part 2 - mutation association

vue.config.js
For a while I have been able to debug JS files like `gquery.js`, but not the JS code in Vue components like `Workflow.vue`. It worked before, but stopped some time ago.
After some searching, found in StackOverflow users saying that the `devtool` configuration had to be `eval-source-map` for the development mode. Tested, and it worked! With that I managed to finish writing the last part about the [ways to debug JS code in Cylc UI](https://gist.github.com/kinow/337c2af7b8bdfa58692d5e415f2876a5) that I am familiar with for the workshop.
Small change, one review should do? It affects only development mode... and only the sourcemap...
=> Use eval-source-map for sourcemap with Vue in development

vue.config.js
From some time ago we started getting a message when building the project about GraphQL lint, and telling us how to disable that warning.
This PR simply disables that, as we are not linting GraphQL queries (which we can do later after #418 for example), removing the warning, and leaving the console output with no other warnings, only the build information now.
=> Remove warning about GraphQL lint when building the project

.github/workflows/main.yml
Was going to checkout another branch when I noticed I had changes from yesterday. I was going to update actions to see if coverage was working again for PR's, but in the end didn't need to update anything (#328).
But had already updated the checkout action, and today I remembered v1 had an issue where if you push too many changes, the PR may get stuck without being able to check out the code. They fixed it in the v2, so it should be a good idea to update it.
One review should do. Best way to review is just wait for GitHub actions to run, and confirm it checked out the code with no issues.
=> Update action checkout from v1 to v2 (avoids possible race issue)

src/components/cylc/gscan/index.js, src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/index.js, src/graphql/queries.js, src/services/gquery.js, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, src/store/workflows.module.js, tests/unit/components/cylc/tree/index.spec.js, tests/unit/components/cylc/tree/tree.data.js, tests/unit/components/cylc/tree/tree.vue.spec.js
These changes close #403, and revert #232 (so that offline mode works again, as `__typename` is created by `ApolloClient` only - i.e. unless you are querying a real endpoint with the client, no `__typename`s are created).
It also creates cyclepoints using GraphQL, instead of iterating over family proxy data in JS (thanks to @dwsutherland).
=> Fix GraphQL alias simplify code, create cycle points from GraphQL, and revert __typename change

src/router/index.js, src/router/paths.js
This should be more clear to quickly see what enables the toolbar or not. I also think this should be less error prone.
This morning I was going to write a e2e test to confirm that the toolbar is present when you visit the workflow route (the one with the Lumino component). I remembered I had broken the toolbar a couple times in the past, and it was also due to renaming routes (workflows, then tree, or treeview, etc).
By not relying on the route name, and instead using a flag in the Route record metadata (also present, a feature of VueRouter) we should reduce the risk of I or others breaking the toolbar again. Will prepare a e2e test for that anyway later as well :+1: 
=> Use a metadata field in each vue route instead of a list of strings

src/components/cylc/tree/index.js, src/graphql/queries.js, src/services/workflow.service.js, src/store/index.js, tests/unit/components/cylc/tree/tree.data.js
We can use a filter in the GraphQL query to filter familyProxies and exclude the `root` family. This removes the need to have an `if` in JS for that.
Also removes a couple of linter issues raised when the dependencies are updated. These changes are from the infinite tree branch, which has several conflicts, but since it depends on the incremental updates, might need more time before it is ready for review and merge.
So applying these changes earlier should allow us to reduce more the size of the infinite tree pull request, making it easier for reviewers later.
=> Remove unnecessary JS code handled in GraphQL query, and fix lint issues

src/components/cylc/tree/TreeItem.vue, src/graphql/queries.js, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, tests/e2e/specs/tree.js
The offline mode is broken again, no big news. **However**, as we now have e2e tests, it is much easier to have a test to confirm that the offline mode is working. Here's what we will have in this PR:
1. Right now it is broken because the GraphQL query used to create mocked data was not updated. So now we parse (Python `re` module) the query value from `src/graphql/queries.js` and use it when generating the mocked data.
2. Functional tests will confirm that the tree component is working in the offline mode. Meaning that if anything breaks it again, the CI will fail in GitHub, and then we can fix before merging the PR.
Hopefully no more PR's from me to fix the offline mode :crossed_fingers: :grimacing: 
Tried to test the things I remember …
=> Add e2e tests for tree view (offline mode)

CHANGES.md, src/components/cylc/workflow/Workflow.vue, src/components/cylc/workflow/index.js, src/views/Workflow.vue
These changes close #431 
Use existing views data `isLoading` that is updated by the `WorkflowService`. When we subscribe a query/view to the service, we pass a callback. So far, the callback has been the same for every view, simply updating a data state for loading.
Then this value gets passed down via props to other components, all the way down to the Lumino widget wrapper component. Which uses that reactive value to display a Vuetify [Skeleton Loader](https://vuetifyjs.com/en/components/skeleton-loaders/). Once data has been received, the service calls the callback which updates the loading state (to false).
And then the skeleton loader disappears and the original component is displayed.
=> Add loading state to Lumino widgets with skeleton loaders

src/lang/en-GB/App.json, src/views/Graph.vue, src/views/Tree.vue, src/views/Workflow.vue
These changes close #422 
We have the user (same from the URL) that is pre-fetched in the Route's. So this PR is simply using that `user.username` to use as parameter in the query, instead of using the workflow name.
This is necessary for #420 , as there the deltas use the workflow ID, not the name.
Further work to support URL's with other user's username is part of another issue :+1: 
=> Use workflow ID instead of workflow name in queries

src/services/mock/workflow.service.mock.js
The e2e tests are currently broken on `master`. This PR should fix that :crossed_fingers: . To review, just wait for GitHub actions and confirm both workflows pass (there's one that runs only the e2e tests).
=> Fix mocked WorkflowService

src/services/workflow.service.js
@hjoliver noticed that the toolbar buttons were not calling the mutations any longer. It was due to some recent changes in the backend (for api-on-the-fly if I recall correctly, to simplify the schema).
@hjoliver I started by trying to add the `Mutation` component as a dropdown menu (as in the design sketches). That way we would move one step closer to what we have in the sketches, and use the same code used in the Mutations view (lumino widget).
Alas I started changing too many files, as I needed specific mutations (`hold`, `stop`, `release`) and these were within the `Workflow` view at the moment. After that gets moved to a place where it can be shared by components (Vuex store?), it should be easier to add the mutations to our views and …
=> Fix mutations in the Toolbar component buttons

CHANGES.md
Found one PR with the wrong link in the changes. One review should do, ignore GitHub actions.
=> Fix PR link in changelog

babel.config.js, package.json, src/model/TaskState.model.js, yarn.lock
=> Update enumify to 2.x

CHANGES.md, package.json, src/App.vue, src/components/core/Alert.vue, src/styles/cylc/_header.scss, src/styles/cylc/_toolbar.scss, src/styles/cylc/_workflow.scss, src/styles/index.scss, src/utils/font-size.js, src/views/UserProfile.vue, src/views/WorkflowsTable.vue, tests/e2e/plugins/index.js, tests/e2e/specs/userprofile.js, tests/unit/utils/font-size.spec.js, yarn.lock
These changes close #141
There is a TODO about #335, but for now it's storing the new font size in the `LocalStorage` (i.e. client-side only).
Under the user profile view, now there is a "Preferences" section, with the Font Size.
- Vuetify appears to be setting the fixed font-size only on `<html>` element, and computing the sizes of other elements relative to that value (rem).
- I've adjusted our code to do the same, except by the Graph component that has some fixed values that I don't dare to change as it would probably cascade the amount of changes necessary and I am not sure if these could be easily fixed
- Reset sets the value from Vuetify sass variable back to the `<html>` element
- The button to increase font size does so with a ratio of 20% for every click, and stores the new value …
=> Change font size

src/model/TaskState.model.js
Mea culpa. Updated the enum but used the wrong param name. One review should do.
=> Fix JSDoc param name

package.json, src/components/cylc/graph/Graph.vue, src/styles/cytoscape/cytoscape-custom.scss, src/styles/index.scss, yarn.lock
Fixing issues found by @hjoliver and posted on RIOT.
1. Scroll bar displayed in the Graph, when viewed in the tabbed/Lumino view (`/#/workflow/five`)
- The `views/Graph.vue` displays the Graph component in full screen, which computes the height as `calc(100vh - 48)`
- The `views/Workflow.vue` displays the Graph component within Lumino, with extra margin/paddings. So `calc(100vh - 48px)` gives a height that is not taking the margin/padding in account, so a scroll bar is displayed.
- This PR changes that so that the Graph HTML element simply does a `height: 100%`, and its parents are CSS-flex. Also sets the layout `core-view` element to have `height: calc(100 - 48px)`, although later we may move this to another element as the toolbar is not …
=> Fix Graph component CSS height, and remove cytoscape-navigator

CHANGES.md, package.json
p.s.: NPM semver schema is a bit more restrictive. I've seen projects using `-SNAPSHOT` or `-alpha.1`. But only the numeric parts are taking into account for the version. The modifier with `alpha.1` can be used too, but it could be confusing for us as we have that in the metapackage 8.0a3. So I just bumped up to the next release number.
=> Prepare for 0.3 release

package.json, src/components/cylc/ConnectionStatus.vue, src/components/cylc/Drawer.vue, src/components/cylc/graph/Graph.vue, src/layouts/Default.vue, src/layouts/Empty.vue, tests/unit/components/cylc/connectionstatus.vue.spec.js, yarn.lock
These changes partially address #465 
Updates to the latest version of Vuetify. Looked at each view of our app, with JupyterHub and `five` running. Everything looks OK.
Kudos to Vuetify developers. They kept backward compatibility as it's not a new major release, and deprecated the values changed, without breaking the user's code. Furthermore, they also added warning messages to each deprecated item, with instructions how to fix it :pray: 
So after updating the version, I simply fixed as they suggested, and then no more warnings in the console.
=> Update Vuetify from 2.2.6 to 2.3.9

src/components/cylc/gscan/GScan.vue, src/components/cylc/gscan/index.js, src/components/cylc/tree/index.js, src/styles/cylc/_gscan.scss, src/styles/index.scss, tests/unit/components/cylc/tree/deltas.spec.js, tests/unit/components/cylc/tree/index.spec.js
Related to https://github.com/cylc/cylc-flow/pull/3724 and https://github.com/cylc/cylc-uiserver/pull/150
This PR contains a patch that allows the UI to show stopped workflows, added in the two issues above.
=> async scan updates for the UI

CHANGES.md, src/components/cylc/tree/Tree.vue, src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/cylc-tree.js, src/graphql/queries.js, src/mixins/treeitem.js, tests/e2e/specs/tree.js, tests/unit/components/cylc/tree/treeitem.vue.spec.js
These changes close #469 
These changes partially address #333 (see https://github.com/cylc/cylc-ui/issues/333#issuecomment-651600058)
Cycle points showing newest data first. Tasks in alphabetical order, by name. Jobs by submit number, reverse (we display the first only, which is the latest).
We do not need to sort the deltas when updating or removing data. As the data returned is used to update existing data and nodes in the UI.
We are also not sorting the cycle points. The reason is that the cycle points are added to the tree one after the other. So if we already have data in the UI, adding new data, even if in order to the JS data, the browser won't display in order. It will just append the new data (in order) after the existing data.
So because of that, the cycle points are returned …
=> Sort tree view by cyclepoints and task names

CHANGES.md, src/layouts/Default.vue, tests/e2e/specs/layout.js
These changes close #465 
Now if an error occurs in the browser console, and if you are not in production mode (we can change this later if others think we should always display the message) it will display an error message.
I hope this will be useful specially when testing the UI with workflows during development. Sometimes the UI may look OK, but you could have hidden errors such as deltas no being applied. Ideally, we should never see that error message. 
This captures errors from children elements of the `Default` layout, that were not captured. Think of it as a `try { renderChildrenOfDefaultLayout } catch { # display error message }`.
=> Add global error catcher with Vue's errorCaptured

CHANGES.md, src/components/cylc/tree/cylc-tree.js, src/components/cylc/tree/index.js, src/graphql/queries.js, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, src/services/mock/one/flow.cylc, tests/e2e/specs/tree.js, tests/unit/components/cylc/tree/deltas.spec.js, tests/unit/components/cylc/tree/index.spec.js, tests/unit/components/cylc/tree/tree.data.js, tests/unit/components/cylc/tree/tree.spec.js
These changes are related to #504 #339 
At the moment every node in the tree has an ID like `kinow|five|1|foo`, except the cycle points, which use just `1` (integer-type).
I implemented that way as it was the simplest approach, and because our cycle points are built from family proxies in the GraphQL query (cycle points are not types in the schema I think). @oliver-sanders found out that we didn't have the ID's while working on the mutations & api-on-the-fly integration.
=> Use cycle point ID in the tree view structure

src/mixins/toolbar.js, src/store/app.module.js, src/store/index.js, tests/unit/store/app.spec.js, tests/unit/store/index.spec.js, tests/unit/store/user.spec.js, tests/unit/store/workflows.spec.js
Trying to increase our code coverage a bit more. There are pieces of code from the theme we downloaded for the very first version of Cylc UI that are not used and can now be removed.
In our tests, we also have a very bad pattern, where the Vuex store is imported and modified during tests. This means that one unit test may modify states in the store that are used by other tests. Making it difficult to run anything in parallel, as well as to add and update tests. I will try to fix that so that we don't end up with flaky tests :+1: 
=> Add more tests for Vuex store, and remove unused code

package.json, src/main.js, yarn.lock
Found this while working on the JupyterLab tests yesterday. While reviewing our dependencies, to see what JupyterLab would need, I spotted this one that I didn't remember why we needed it.
Some `git-log`'ing later, I remembered it came with the Tim Creative theme that we used for the first versions of Cylc UI.
https://github.com/vuejs/vuex-router-sync
The `vuex-router-sync` library adds a `store.state.route` attribute to the Vuex store's state. This `route` attribute represents the current route. We haven't had to use this yet, so safe to remove IMO.
=> Remove vuex-router-sync dependency and code.

.github/workflows/main.yml, CONTRIBUTING.md, package.json
This fixes an issue whereby, running e2e tests results in error if NODE_ENV is not set to offline. 
Thanks to @kinow for the fix!
=> Add offline mode to e2e tests

src/components/cylc/gscan/GScan.vue, src/styles/cylc/_gscan.scss, tests/unit/components/cylc/gscan/gscan.vue.spec.js
=> Tweak CSS flex/overflow values for GScan workflow names, to avoid word-break, and hidden job statuses

src/model/TaskState.model.js, src/utils/tasks.js, tests/unit/components/cylc/tree/tree.data.js, tests/unit/components/cylc/tree/tree.spec.js
=> Remove retrying and submit-retrying states

.nycrc, babel.config.js, package.json, tests/e2e/plugins/index.js, tests/e2e/specs/userprofile.js, yarn.lock
Thought it was strange that my last PR's the coverage wasn't increasing as much as I expected. Something happened some commits ago, and looks like the e2e reports are empty. We are still not too bad, with about 70% for unit tests coverage :partying_face: 
Let's hope this PR fixes e2e coverage, and that the reported number is good as.
=> Fix e2e coverage

src/components/cylc/gscan/GScan.vue, src/model/WorkflowState.model.js
* Switch octagon pause icon for circular equivalent.
* Add stopped and stopping icons.
* Learn how to use enumify, nice, will make more use of this.
* Add icons to the WorkflowState enumeration.
* Remove surplus `toLowerCase()` calls.
* Add tooltip for workflow state (in-case the icons are not clear enough).
=> gscan: add icons for stopping and stopped flows

CHANGES.md, src/components/cylc/gscan/GScan.vue, src/graphql/queries.js, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, tests/e2e/specs/gscan.js, tests/unit/components/cylc/gscan/gscan.data.js, tests/unit/components/cylc/gscan/gscan.vue.spec.js
These changes close #337
Improves the `GScan` component adding
- minus hosts and versions filtering
=> Add search and filter functionalities to GScan

CHANGES.md, src/views/Dashboard.vue, tests/e2e/specs/dashboard.js
Fixing issue reported by @hjoliver on Element, where he would get the icons in the dashboard with a really large width/height. I reproduced the issue, but instead of large icons, my dashboard had no icons at all.
From what I could tell, something might have changed in Vuetify, where the parent element VList or VListItem stopped giving the right dimensions, and instead returned large or invalid values, causing the icon—which inherits the height and widget—to be either very large or hidden.
=> Fix icons in the Dashboard

src/components/cylc/gscan/GScan.vue, src/components/cylc/tree/Tree.vue, src/components/cylc/tree/TreeItem.vue, src/styles/cylc/_gscan.scss, tests/unit/components/cylc/gscan/gscan.vue.spec.js
These changes partially address #502 
For the hierarchy in GScan, we don't need/want to re-create a tree/treeitem components pair. Instead, we should be able to use Vue's [components slots](https://vuejs.org/v2/guide/components-slots.html).
This PR was part of the hierarchy PR for GScan. That PR, however, will take a bit longer to be ready to be merged. And other PR's pending review will also modify the GScan component. So having this simpler PR will make it easier, I think, to merge this change and simplify the hierarchy PR to GScan.
=> Add slots to the Tree and Tree item components, and then use Tree component in GScan

CHANGES.md, src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/index.js, src/styles/cylc/_job.scss, src/styles/cylc/_tree.scss, tests/e2e/specs/tree.js
In #530 , I moved the job-details out of the template, into the JavaScript code and as a node in the tree.
This way, we control whether it is expanded by clicking on the expand/collapse icon, as with other icons.
Yesterday while I was testing #543, making sure I didn't forget @oliver-sanders ' mutations work when fixing conflicts, I realized clicking on the Job icon would
1. expand the node
2. display the pop up with the mutations context menu
By using the expand/collapse icon, we avoid expanding nodes or displaying the context menu unnecessarily.
=> Make job-details a node in the tree, expand/collapse control, align tree-leaf-triangle

.github/workflows/main.yml, package.json, tests/e2e/specs/layout.js, tests/e2e/specs/toolbar.js, yarn.lock
I've been getting a really old Cypress V3, not sure if that was on-purpose.
Trying to get Cypress to pick up my installed browser I bumped it to V6 which kinda worked in that it picked up my browser, but I then get "Whoops, we can't run your tests". Progress is getting a different error ...
=> cypress: upgrade from V3 to V6

CHANGES.md, src/components/cylc/gscan/GScan.vue, src/components/cylc/tree/TreeItem.vue, src/styles/cylc/_tree.scss
These changes close #576 
What it looks like after this change:
See linked issue for description and screenshots of the before.
=> Responsive GScan, handle workflows with long names

src/components/cylc/gscan/GScan.vue, src/model/WorkflowState.model.js, tests/unit/components/cylc/gscan/gscan.vue.spec.js
These changes close #553 
There were new states added (`STOPPING`, and `ERROR`). So now the code is using `Enumify`'s `enumOrdinal` to sort these values. They are based on the order the enum values are declared. At the moment the order is:
- RUNNING
- HELD
- STOPPING
- STOPPED
- ERROR
Also remove the now redundant `.toLowerCase` as the enums are already using the lower case string, and uses the `WorkflowState` enum to create the list of filters. We were missing stopping and another state that were included after the filters were initially written for GScan.
The unit tests should cover most of GScan. The only part covered exclusively by e2e tests, are the watchers, as that's easier to test with an e2e, rather than changing values and making sure we wait for the watcher to be triggered in …
=> Sort other states, remove unnecessary Enum.toLowercase, use Enum for Workflow state filters, and add more tests for GScan

yarn.lock
Small issue. I noticed this one yesterday while running tests. The console has the following warning:
```
Browserslist: caniuse-lite is outdated. Please run:
npx browserslist@latest --update-db
```
I executed the command above, which reported:
```
caniuse-lite has been successfully updated
Target browser changes:
- and_chr 84
+ and_chr 88
- and_ff 68
+ and_ff 83
- chrome 84
- chrome 83
+ chrome 88
+ chrome 87
+ chrome 86
- edge 84
- edge 83
+ edge 88
+ edge 87
- firefox 79
- firefox 78
+ firefox 84
+ firefox 83
- ios_saf 13.4-13.5
- ios_saf 13.3
+ ios_saf 14.0-14.3
+ ios_saf 13.4-13.7
- op_mob 46
+ op_mob 59
- opera 69
- opera 68
+ opera 72
+ opera 71
- safari 13
+ safari 14
- samsung 11.1-11.2
+ samsung 13.0
```
Created this PR as …
=> Update list of browsers fixing warning

src/components/cylc/Task.vue, src/components/cylc/gscan/GScan.vue, src/components/cylc/tree/Tree.vue, src/components/cylc/workflow/Toolbar.vue, src/model/TaskState.model.js, src/utils/tasks.js, tests/e2e/specs/tree.js, tests/unit/components/cylc/gscan/gscan.vue.spec.js, tests/unit/components/cylc/toolbar.vue.spec.js, tests/unit/components/cylc/tree/deltas.spec.js, tests/unit/components/cylc/tree/tree.spec.js, tests/unit/components/cylc/workflow/toolbar.vue.spec.js, tests/unit/utils/tasks.spec.js
Minor tweaks to get all the task icons working properly on master.
- remove vestiges of the obsolete held task state
- corrected several uses of `submit_failed` to `submit-failed`
- use `WorkflowState` instead of `TaskState` in a bunch of places
- make the queued state get recognized properly (it hasn't been removed quite yet)
Result:
- queued tasks (correctly) get the waiting icon, not the unknown state icon
- nonexistent held state removed from state filter drop-down
- submit-failed and queued get the correct icon in the state filter drop-down
Note this overlaps a little with #575 but that might not be merged for a little while.
=> Fix task states.

.github/workflows/main.yml
Use the standard action to configure node to:
* Pin the version.
* Ensure we are using the standard setup.
=> pin node version in github actions

CHANGES.md, src/components/cylc/gscan/GScan.vue, src/components/cylc/tree/Tree.vue, src/components/cylc/workflow/Lumino.vue, tests/unit/components/cylc/tree/tree.vue.spec.js
=> Add collapse all and expand all buttons to Tree component

.github/workflows/auto_publish_release.yml, .github/workflows/create_release_pr.yml, CHANGES.md, package.json
These changes close #475 
Adds two new workflows, with the same names as in isodatetime (which I used as reference). The first just creates a PR with updated changelog date, and `package.json` version. Merging that PR triggers the second PR which will create the release/tag, upload the generated production build, and add comments.
The `package.json` is updated too to use `0.3.0-0`. That's the equivalent of Python's `0.3.0dev`, or Java's `0.3.0-SNAPSHOT`. A pre-release as in https://semver.org/ (see item 9).
With all that done, we can safely update our Conda Forge recipe with the sha25sum value, and the zip URL. Credits go to @MetRonnie & @oliver-sanders who did most of the work I copied to automate this release.
=> Automate release

src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/cylc-tree.js, src/components/cylc/tree/deltas.js, src/components/cylc/tree/index.js, src/graphql/queries.js, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, tests/unit/components/cylc/gscan/gscan.data.js, tests/unit/components/cylc/tree/tree.data.js
This is a small change with no associated Issue: remove "latest message" item currently shown in task job leaves.
"Latest message" is a hold-over from the old GUI tree/table view, which could not accommodate more than one message.
In the new UI:
- standard messages correspond to task job status (no need to show)
- non-standard messages registered as job outputs will be shown by #530 
- (we should display other non-standard messages: e.g. warnings and messages not used for triggering: #595)
=> Remove useless job latestMessage item.

CHANGES.md, src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/cylc-tree.js, src/components/cylc/tree/index.js, src/graphql/queries.js, src/model/TaskOutput.js, src/services/mock/checkpoint/get_checkpoint.py, src/services/mock/workflow.service.mock.js, src/styles/cylc/_tree.scss, tests/e2e/specs/tree.js, tests/unit/components/cylc/tree/index.spec.js, tests/unit/components/cylc/tree/tree.data.js, tests/unit/components/cylc/tree/tree.spec.js, tests/unit/components/cylc/tree/tree.vue.spec.js
=> Display message triggers

CHANGES.md, src/components/cylc/workflow/Toolbar.vue, src/services/mock/workflow.service.mock.js, src/utils/aotf.js, tests/e2e/specs/aotf.js
addresses: #339 
built on: #544 
related sibling pr: https://github.com/cylc/cylc-uiserver/pull/175
Add a button in the workflow toolbar that lists workflow mutations.
=> aotf: toolbar mutate button

src/components/cylc/Mutation.vue, src/components/cylc/cylcObject/Menu.vue, tests/e2e/specs/mutation.js
Small fix, make sure the form is properly reset.
Fixes a bug where inputs made to one mutation on one task could be "remembered" when you open the mutation editor for the same mutation but on a different task. After this change no information entered into the mutation editor should be "remembered" from one task to another.
It was kinda useful in some respects to have the values from the last mutation remembered, however, in its current for it is unsafe so better to reset everything.
Tricky to test, any e2e test would need to be written into the structure of the form generator which would be fragile.
=> aotf: reset forms correctly

src/components/cylc/tree/TreeItem.vue
completes point one of #333 
Swap the job and task name for readability.
=> tree: swap task name and job order

src/components/cylc/Task.vue, src/styles/cylc/_task.scss, src/styles/cylc/_tree.scss
See https://github.com/cylc/cylc-ui/issues/605#issuecomment-795197316
Boost the task icon size in the tree view by 20%.
(Related to #605 but that is a different issue about a global configuration for scaling these icons in all contexts.)
Before:
After:
=> tree: boost task icon size 20%

CHANGES.md, src/components/cylc/Mutation.vue, src/components/cylc/Task.vue, src/components/cylc/tree/Tree.vue, src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/cylc-tree.js, src/model/TaskState.model.js, src/styles/cylc/_job.scss, src/styles/cylc/_task.scss, src/views/Guide.vue, tests/unit/components/cylc/tree/index.spec.js, tests/unit/components/cylc/tree/tree.spec.js, tests/unit/model/taskstate.model.spec.js
closes #563
Also:
* Upgrade the Guide page from Vuetify1->2
* Use the task state enum in the Guide to keep it in sync with task state changes.
* Change the submitted task colour
* see also https://github.com/cylc/cylc-flow/pull/3831
* note the terminal colours need to be more vibrant so don't match
Start a CSS3 animation for each `<task :status="running" />` component that will keep the progress clock-face up to date for the life of the running job.
This saves having to routinely compute the progress and should, hopefully, be pretty efficient.
Example screen grab, the page is reloaded a few times to show that the animations are started with the correct offset for tasks that are already running before the page is loaded.
=> task: update progress with css animation

src/utils/aotf.js, tests/unit/utils/aotf.spec.js
Quick bugfix for a small bug.
Mutations with required arguments that are cylc objects (e.g. tasks, cycle points, etc) would show up as not requiring additional information even when they did.
Example: the `set_hold_point` mutation introduced in the cylc-pause branch (currently still a PR on cylc-flow).
=> aotf: fix small bug in mutation filtering

src/components/cylc/gscan/GScan.vue, src/components/cylc/workflow/Toolbar.vue, src/model/WorkflowState.model.js, src/utils/aotf.js, tests/e2e/specs/aotf.js, tests/e2e/specs/gscan.js, tests/unit/components/cylc/gscan/gscan.vue.spec.js
Companion to https://github.com/cylc/cylc-flow/pull/4076
> **tldr:** We have separated the concepts of holding workflows and holding tasks within workflows.
>
> * Holding and releasing workflows is now play/pause.
> * Holding and releasing tasks is now hold/release.
=> cylc-pause: change held->paused

CHANGES.md, src/utils/aotf.js
Attempt to detect errors from called mutations and present them to the user:
=> aotf: display mutation errors

CHANGES.md, src/components/cylc/tree/deltas.js, tests/unit/components/cylc/tree/deltas.spec.js
These changes partially address #614
When the deltas are applied to the existing tree data, multiple may fail. The current `Alert` component shows only a single message. So I've left the `console.error` entry, as it also contains more information such as the complete delta that was dropped.
This way the user will see an alert on the UI showing the latest message. But the console log will contain the other errors.
=> Alert the user if there are any errors processing the deltas

CHANGES.md, src/components/cylc/cylcObject/Menu.vue, src/components/cylc/cylcObject/plugin.js, src/services/mock/workflow.service.mock.js, src/services/workflow.service.js, src/styles/cylc/_aotf.scss, src/styles/index.scss, src/utils/aotf.js, tests/e2e/specs/aotf.js, tests/e2e/specs/mutation.js
closes #621 
addresses #622
Before:
After:
Lessons learned:
* The `dense` prop doesn't really help with space efficiency and makes the fonts go nasty.
* Easier to get layout/style right without using the `v-list` component, however, hard to get the hover effects standard without it.
Screengrab:
=> aotf: niceify menu and pre-filter mutations

src/components/cylc/workflow/Toolbar.vue, src/styles/cylc/_toolbar.scss, src/views/Workflow.vue
Fix a small responsive display bug using a float trick.
Also had a go at centralising the view logic so we don't have to manually write out each view. One day views should be pluggable things that users could contribute.
Before:
After:
=> toolbar: fix line break for narrow displays

CHANGES.md, src/components/cylc/tree/cylc-tree.js, tests/unit/components/cylc/tree/tree.spec.js
These changes close #644 
Workflow used:
```cylc
[scheduling]
cycling mode = integer
initial cycle point = 9
final cycle point = 12
runahead limit = P12
[[graph]]
P1 = "10 => 1 => 2 => 100 => 1000"
[runtime]
[[10]]
script = "sleep 5"
[[1]]
script = "true"
[[2]]
script = """
if [[ "${CYLC_TASK_SUBMIT_NUMBER}" -gt 3 ]]; then
true
else
false
fi
"""
[[[job]]]
execution retry delays = 3*PT1S
[[100]]
script = "true"
[[1000]]
script = "sleep 5"
```
Then just `CTRL + C` after Task `2` gets a couple jobs to check it's adding items in-order.
(see how `9` is coming **after** `10` :point_up:  ­— at the moment we have the oldest cycle points at the bottom)
=> Avoid re-sorting a sorted array, instead adding element in its sorted index (respecting locale, and numeric on)

src/styles/cylc/_tree.scss
Boost the job icon size in the tree view 20% (inline with the task icon).
The icons were a bit small, especially now we have the multi job icon.
*before*
*after*
=> tree: job icon size

CHANGES.md, src/components/cylc/tree/cylc-tree.js, tests/unit/components/cylc/tree/tree.spec.js
These changes close #666
@oliver-sanders could you test and see if this solves the issue for your workflow? I tested on `five`, and noticed that when the job started running, the cycle point icon never changed. Then, after this change, it was correctly updated. Thanks!
=> Update the cycle point icon state

CHANGES.md, src/components/cylc/tree/cylc-tree.js, src/views/Tree.vue, src/views/UserProfile.vue, src/views/Workflow.vue, tests/e2e/specs/userprofile.js, tests/unit/components/cylc/tree/tree.spec.js
These changes close #333 
A draft for discussion I think. @oliver-sanders , @hjoliver I've added a setting under the User Profile page. If you change that setting, then reload the tree view (or just navigate after you've set the value), then it should be displayed with the correct order.
=> Allow user to set the order of cycle points

src/components/cylc/gscan/GScan.vue, src/styles/cylc/_gscan.scss
Another iteration on responsiveness for GScan. Noticed this while testing GScan for recent PR's. The flex-basis ratio of `40/60` worked well in the past. But after we got more states displayed in GScan, it didn't work that well.
The reason is that 5 states, with the icon now bigger, passes the flex-basis limit we set. That, combined with flex-wrap, cause the GScan workflow row to grow.
Tested with a really long workflow name, and hacking the code to allow several states. Then adding more than 5 states. Screenshots below show what it looks like after this PR.
=> Remove flex-basis and flex-wrap from gscan

CHANGES.md, src/components/cylc/cylcObject/plugin.js
* closes #690
Sadly not possible to test at the moment as we would require a second workflow.
=> aotf: make mutation menu directive reactive

CHANGES.md, src/components/cylc/common/deltas.js, src/components/cylc/tree/deltas.js, src/graphql/queries.js, tests/unit/components/cylc/tree/deltas.spec.js
These changes:
- close #689 
- close #556 
=> Use WorkflowState to control Tree view state, ignoring the shutdown property

.github/workflows/main.yml
These changes close #590 
We've updated to yarn v3. I think macos build should work fine now? It passed on my fork's GH actions. I'll retrigger it a couple times now to confirm it's working OK.
=> Add back macos to test matrix

src/model/WorkflowState.model.js, src/views/Dashboard.vue, tests/e2e/specs/dashboard.js
These changes close #693 
The fix uses an array of enums to sort the states displayed in the Dashboard view. I copied this array from this PR that is currently under review: #703 
Pushing to 0.6.0 since I think we are releasing 0.5.0 now and this would take a while to review.
=> Use an array of enums to define order in the Dashboard

CHANGES.md, src/components/cylc/common/deltas.js, src/components/cylc/common/sort.js, src/components/cylc/gscan/GScan.vue, src/components/cylc/gscan/filters.js, src/components/cylc/gscan/nodes.js, src/components/cylc/gscan/sort.js, src/components/cylc/tree/index.js, src/components/cylc/tree/nodes.js, src/components/cylc/tree/sort.js, src/services/mock/json/GscanSubscriptionQuery.json, src/store/workflows.module.js, src/styles/cylc/_gscan.scss, tests/unit/components/cylc/gscan/gscan.vue.spec.js
Related to #139 
* Brings hierarchy into GScan, using existing Tree, TreeItem, Job, and Task components.
* Creates modules for `sort`, `filter` (will spread this pattern to other components over next PR's/days/weeks/...).
* Makes the filter workflow name field case-insensitive (i.e. searching for `RUN1` will include a workflow like `five/run1`).
* Has a known bug in sorting by status, see comment below, and pending #703 
* I think I could try some performance improvements, for instance, for every delta received it goes over the tree, finds the next insertion index, filters, etc... if you have 40 workflows, you will receive 40 workflows. We could debounce it and run this every second or every 500ms, giving time for more deltas to be applied and reduce computation in JS and DOM updates …
=> Hierarchical GScan

src/components/cylc/gscan/GScan.vue, src/components/cylc/tree/Tree.vue, src/styles/cylc/_gscan.scss, src/views/Tree.vue
These changes close #730 
The Tree component now has no borders, padding, margin, etc. This way the caller code can choose whether to add them or not.
For the Tree **view** we want padding to match the previous appearance. But for GScan we don't want any padding or spaces so that the hover effect occupies as much space as possible without distracting users.
=> Remove margin/padding from Tree component

src/views/Dashboard.vue
This is a very small change with no associated Issue.
Fixes broken link which was pointing to https://cylc.github.io/cylc-doc/latest/html/suite-design-guide/index.html
Also changed the description in line with the decision that rose suites should not be changed to workflows.
=> Fix broken workflow design guide link

CHANGES.md, src/graphql/graphiql.js, src/graphql/index.js, src/mixins/graphql.js, src/model/User.model.js, src/services/user.service.js, tests/unit/mixins/graphql.spec.js
jupyter_server: support Cylc UIS Jupyter Server extension
* https://github.com/cylc/cylc-uiserver/pull/230
* The UIS is now a Jupyter Server extension.
* The endpoint is now `cylc/#/` rather than `#/`
* Authentication via token/cookie is now supported.
* Sets XSRF header to support new hubless single-user mode.
* closes https://github.com/cylc/cylc-ui/issues/679
=> Jupyter server

src/components/cylc/tree/deltas.js
These changes close #667 
It will basically handle any `deltas.added.workflow` as an initial-data-burst. Previously, only the workflows with status=running would be handled.
With this, executing the mutation to reload the workflow does not break the tree view :+1: 
=> Handle any deltas.workflow.added as an initial-data-burst

src/graphql/merge.js, src/services/workflow.service.js, tests/unit/graphql/merge.spec.js
These changes:
- close #439 
- close #417 (throws an error warning the developer that what s/he is doing is wrong)
- close #300 (throws an error for certain types (e.g. boolean, string, numeric if values are different; but for lists & objects they are combined/concat'ed))
I squashed commits and push-forced successive commits. I think that confused codecov, so ignore its message in this PR and look at the codecov output. ATOW:
=> Merge GraphQL query Documents

src/graphql/merge.js, tests/unit/graphql/merge.spec.js
=> Merge lists using a for-loop instead of unionBy

src/components/cylc/cylcObject/plugin.js, src/components/graphqlFormGenerator/FormGenerator.vue, src/components/graphqlFormGenerator/FormInput.vue, src/styles/cylc/_mutation_form.scss, src/styles/cylc/_tooltip.scss, src/styles/index.scss, tests/unit/components/graphqlFormGenerator/formgenerator.vue.spec.js
I made these changes while continuing to explore the UI codebase. Turns out this partially addresses #647
- Fix line breaks in markdown content and adjust style of mutation edit form description expansion panel
| Before | After |
| --- | --- |
| ![image][before-collapsed] | ![image][after-collapsed] |
| ![image][before-expanded] | ![image][after-expanded] |
(Note the grey highlight when hovering on the expansion panel appeared in both "before" and "after" , it just didn't happen to get captured for the "before" screenshots)
- Also implement a max-width for all tooltips
[before-collapsed]: https://user-images.githubusercontent.com/61982285/138328312-ba2106c2-7519-4f18-8c4e-360c2eafa361.png
[before-expanded]: https://user-images.githubusercontent.com/61982285/138328637-206af2c5-ef30-4c0a-9d5 …
=> Improvements to tooltips and mutation edit form 

CHANGES.md, src/components/cylc/Header.vue, src/components/cylc/cylcObject/Menu.vue, src/lang/en-GB/UserProfile.json, src/lang/pt-BR/UserProfile.json, src/model/User.model.js, src/services/mock/json/userprofile.json, src/services/user.service.js, src/utils/aotf.js, src/views/UserProfile.vue, tests/e2e/specs/aotf.js, tests/e2e/support/graphql.js, tests/unit/model/user.model.spec.js
Putting this up as an initial PR to disable buttons for mutations that are not authorized.
I have not dealt with the tooltip, the `"workflow-play-pause-button"` or `"workflow-stop-button"` yet, will do a follow-up pr for those. 
This branch requires it's sibling PR: https://github.com/cylc/cylc-uiserver/pull/204
These changes partially address https://github.com/cylc/cylc-ui/issues/704
Changes look as follows: 
For `userB`, accessing `userA`'s ui-server with the following auth permissions in UserA's config files:
```
c.UIServer.site_authorization = {
"*": {
"*": {
"default": ["ALL"],
"limit": ["ALL"],}
}
}
c.UIServer.user_authorization = {
'userB': ['READ', 'trigger']
}
```
Going to : `/userA/userprofile`, when authenticated as `userB` will look as follows:
And, clicking on the mutation …
=> Disable unauthorized buttons

src/components/cylc/workflow/Toolbar.vue
built on #805
This completes the play-pause/resume-stop sequence in the workflow toolbar.
=> Toolbar play from stopped

src/styles/cylc/_workflow.scss
=> Improve style of Lumino tab close button

.github/workflows/main.yml
Just simplifying GH Actions test workflow according to https://github.com/actions/setup-node/blob/main/docs/advanced-usage.md#caching-packages-dependencies
=> GH Actions: Simplify caching

package.json, src/components/cylc/Drawer.vue, src/components/cylc/gscan/GScan.vue, src/components/cylc/table/Table.vue, src/components/cylc/table/deltas.js, src/components/cylc/tree/Tree.vue, src/styles/index.scss, src/views/Table.vue, src/views/Tree.vue, src/views/Workflow.vue, tests/e2e/specs/table.js, tests/e2e/specs/tree.js, tests/unit/components/cylc/table/deltas.spec.js, tests/unit/components/cylc/table/table.data.js, yarn.lock
This merge request updates the design and functionality of the table and tree views. It includes;
- removed the requirement to manually 'submit' filtering options in the filter bar
- fixed the filter bar to the top of the Lumino container in the table view
- added a new column with a dropdown toggle to the task rows (if they have current jobs)
- modified the table data store to include information about the jobs relating to the current task (and add, update and remove as instructed via delta changes)
- modified the table to list the task jobs' when the jobs dropdown toggle is applied
- fixed the display of the 'layered' task status icon
- added the job status icon and submission number in the job rows
- updated the respective tests
These changes partially address #471
These changes:
- …
=> Updates to View filtering, and table display and functionality

src/components/cylc/cylcObject/Menu.vue, src/components/cylc/cylcObject/plugin.js, src/styles/index.scss, tests/e2e/specs/menu.js, tests/e2e/specs/tree.js
=> Prevent mutation menu closing when clicking on another task or cycle

src/components/cylc/gscan/nodes.js
These changes close #930, fixing a bug where the GScan sidebar was only showing the top level of workflow directory trees.
=> Fix incorrect nesting of hierarchical dirs in GScan

src/components/graphqlFormGenerator/components/List.vue
Attempt to focus the latest element when the add button is pushed in the mutation menu. This works but is not ideal because of the use of two 'Vue.nextTick' calls, but Im not sure refactoring the markup to not have this requirement is worth it for the amount of value this ticket will add.
These changes close #890
=> Focus the latest input box created when user clicks add button

README.md, tests/unit/components/cylc/gscan/gscan.vue.spec.js
Also make chai print whole objects in gscan test failures instead of the incredibly useful `{ ...(5) }`
=> Add useful unit tests opts to README

.codecov.yml, .github/workflows/main.yml, README.md
These changes close #918. No more codecov comments ✨ replaced with CI "Checks"
Also removed link to anaconda page
=> Add codecov config

package.json, tests/.eslintrc.js, tests/e2e/.eslintrc.js, tests/e2e/specs/dashboard.js, tests/e2e/specs/table.js, yarn.lock
There were 2 tests where `.only()` was seemingly accidentally committed, leading to other tests in those files being excluded. This PR removes those `.only()`s and adds https://github.com/levibuzolic/eslint-plugin-no-only-tests to prevent it happening again.
=> Use eslint-plugin-no-only-tests

src/components/cylc/Toolbar.vue, src/components/cylc/cylcObject/Menu.vue, src/components/cylc/workflow/Toolbar.vue, src/styles/cylc/_toolbar.scss, src/styles/index.scss
These changes partially address #955
| Before | After |
| --- | --- |
| ![vld710_8000_user_rdutta_cylc__redirects=1(iPhone SE)](https://user-images.githubusercontent.com/61982285/158844002-da9cf030-da6a-4f0b-8814-2390a5bb204d.png) | ![vld710_8000_user_rdutta_cylc__redirects=1(iPhone SE) (1)](https://user-images.githubusercontent.com/61982285/158844004-abd995d9-94b6-4cf0-a255-ba8df07b4ec6.png) |
=> Improve display of workflow toolbar on narrow viewports

src/components/graphqlFormGenerator/components/vuetify.js, src/utils/aotf.js
To accompany https://github.com/cylc/cylc-flow/pull/4739
This allows the "trigger" mutation to be run without providing additional context (i.e. you shouldn't need to go through the mutation editor unless you want to fiddle with the defaults) and performs flow validation client-side.
=> aotf: support flow arguments

src/model/User.model.js, src/services/mock/json/userprofile.json, src/services/user.service.js, src/views/Dashboard.vue, tests/e2e/specs/dashboard.js, tests/e2e/specs/table.js
The cylc hub button on the dashboard used to be available in single user mode (`cylc gui`). If clicked this resulted in a 404 page.
This change adds a condition that the gui mode should be multi-user if the button is to display.
I am not sure the preference on the links in the dashboard if the cylc hub button is not visible.
I have stuck with keeping the help links to the right, and the functional links to the left; as currently is the case. I think this looks a little lopsided in single user mode. I’m happy to move the Cylc UI Quickstart to the left list and move the cylc hub to the right for aesthetics. 
In single user mode the dashboard now looks as follows: 
In multi-user mode: 
These changes close https://github.com/cylc/cylc-ui/issues/737 
Sibling: …
=> Remove cylc hub button in single user mode

src/components/cylc/workflow/Toolbar.vue, src/services/workflow.service.js
Close https://github.com/cylc/cylc-ui/issues/998
=> aotf: fix mutations in workflow toolbar

docs/authentication/jwt/package-lock.json, docs/authentication/jwt/package.json, package.json, tests/e2e/specs/graphiql.js, yarn.lock
:champagne: #1000
I set up Renovate on my fork a while back and left it running to see how it got on. It managed to bump a few deps and generally seemed more advanced than dependabot e.g. it raised a PR to bump Vue to V2 raising a bunch of related deps at once. It also gives usage info and nice changelogs. Worth considering see #944.
The GraphiQL update seems to fix https://github.com/cylc/cylc-uiserver/issues/328 for me.
- axios 0.26.0 to 0.27.0
- graphiql 1.5.1 to 1.8.0
- graphql 15.7.2 to 15.8.0
- eslint-plugin-promise 5.1.1 to 6.0.0
- sass 1.49.0 to 1.51.0
- sinon 12.0.1 to 13.0.0
- standard 16.0.4 to 17.0.0
- Replaces: #957
=> Update deps 2

.github/workflows/main.yml, src/services/mock/.eslintrc.js, tests/.eslintrc.js
This is a small change with no associated Issue. Follow-up to #978 
The eslint plugin `no-only-tests` was preventing using `it.only()` locally. This PR makes it enabled only in production mode.
=> Eslint: use `no-only-tests` in production only

.github/dependabot.yml, .gitignore, renovate.json
This is a small change with no associated Issue, follow-up to #1007 
=> Renovatebot labels; bring back Dependabot for GH Actions only

package.json, yarn.lock
This is a small change with no associated Issue. Follow-up to #1016
From the changelog of eslint-config-standard:
> **`eslint-config-node` has been replaced with the up to date fork `eslint-config-n`.** If you have used comments like `// eslint-disable-line node/no-deprecated-api` you now have to reference the `n/` rules instead.
=> Remove dependency on eslint-plugin-node

package.json, yarn.lock
* Closes https://github.com/cylc/cylc-ui/security/dependabot/43
* bump nodemon
- nodemon: 2.0.15 -> 2.0.19
* resolve
- update-notifier: ^5.1.0 => ^6.0.0
(note these are dev deps)
=> deps: bump transitive "got" dependency to v12

yarn.lock
Closes https://github.com/cylc/cylc-ui/security/dependabot/6
Bump a transitive dependency to a patched version to get around a security issue.
=> deps: bump transitive nth-check dependency

yarn.lock
* Mocha pins all its deps to hardcoded versions so we didn't get the
bugfix.
* The [changelog](https://github.com/ai/nanoid/blob/main/CHANGELOG.md#32)
shows a single feature added.
* It's a test dependency so if there are issues they should show
themselves.
* Closes https://github.com/cylc/cylc-ui/security/dependabot/28
=> deps: bump nanoid 3.1.20 => 3.3

package.json, yarn.lock
Closes:
* https://github.com/cylc/cylc-ui/security/dependabot/9
* https://github.com/cylc/cylc-ui/security/dependabot/10
* https://github.com/cylc/cylc-ui/security/dependabot/13
* https://github.com/cylc/cylc-ui/security/dependabot/29
* https://github.com/cylc/cylc-ui/security/dependabot/30
* https://github.com/cylc/cylc-ui/security/dependabot/31
Explanation:
* The selfsigned dependency is brought in by webpack-dev-server which is a dev dep used in testing.
* Resolve selfsigned dep to v2.
* v2.0.0 is the same as v1.10.14 but with the node-forge dep bumped so shouldn't cause issues with webpack-dev-server.
Tried out `yarn run serve`, everything seemed to be working fine.
=> deps: bump selfsigned 1.10.14 => 2.0.1

package.json, yarn.lock
Remove direct dependencies on:
- svgo (added for since-removed graph view in #289)
- cross-env (added for karma/jasmine in #24, since switched to mocha)
=> Trim unused dependencies

CHANGES.md, src/components/cylc/Drawer.vue, src/components/cylc/Header.vue, src/components/cylc/Mutation.vue, src/components/graphqlFormGenerator/FormGenerator.vue, src/components/graphqlFormGenerator/FormInput.vue, src/components/graphqlFormGenerator/components/Enum.vue, src/components/graphqlFormGenerator/components/List.vue, src/components/graphqlFormGenerator/components/NonNull.vue, src/components/graphqlFormGenerator/components/vuetify.js, src/plugins/vuetify.js, src/styles/_util.scss, src/styles/cylc/_drawer.scss, src/styles/cylc/_toolbar.scss, src/styles/index.scss, src/views/Tree.vue, tests/e2e/specs/aotf.cy.js, tests/e2e/specs/mutation.cy.js, tests/e2e/specs/workflow.cy.js
These changes partially address #885
Improve mutation form validation:
- Make validation errors more prominent with red colour
- Submit button turns red with warning tooltip if there are validation errors (do not disable completely because we leave control to the user)
- Improve/fix some of the validation rules for various inputs
- The broadcast cycle point input validation needs https://github.com/cylc/cylc-flow/pull/5007 but this can be merged before that
It does not address having empty lists in the form, as mentioned in the issue #885
=> Form validation

src/components/cylc/cylcObject/Menu.vue, src/styles/cylc/_menu.scss, tests/e2e/specs/aotf.cy.js, tests/e2e/specs/mutation.cy.js
=> made mutation edit button x-large to make it easier to click.

CHANGES.md, src/components/cylc/table/Table.vue, tests/unit/components/cylc/table/table.data.js, tests/unit/components/cylc/table/table.vue.spec.js
These changes close #1002 
Make the default sort order of the table view match the the tree view. It should respect the "Latest cycle point on top" setting in the UI settings.
I'd appreciate some help with testing this. Going to try and work it out myself as an excercise in getting used to JS & Cypress.
=> Reversed the default sort order of jobs in the table view.

CHANGES.md, cypress/component/cylc-icons.cy.js, src/components/cylc/table/Table.vue, src/components/cylc/table/sort.js, tests/unit/components/cylc/table/sort.spec.js, tests/unit/components/cylc/table/table.data.js, tests/unit/components/cylc/table/table.vue.spec.js
These changes close #1086
Table view column sorting changes:
- Use natural sort for cycle points column (so that e.g. 9 appears before 10 in ascending order for integer cycling mode).
- Sort datetimes (e.g. "start time", "submitted time") so that blanks come after actual datetimes in ascending order
- Simplify to use Vuetify's `v-data-table` built-in sorting.
=> Table view: use natural sort order for cycle point column

CHANGES.md, src/components/cylc/table/Table.vue
These changes close #1121 
As well as modifying the numbers of tasks per page I turned on the table [dense mode](https://vuetifyjs.com/en/components/data-tables/#slots) - I don't think it loses owt, and gains more space:
I've provided 20, 50, 100 and 200 - I couldn't find any way of defaulting to 20 but having 10 available - It's fine even on a small screen:
Additionally I tried it with a workflow with 600 tasks per cycle and it seemed to be as performant as one might reasonably expect (200 took under a second, 2400 took about 5).
Finally, since it's a simple change I added a first and last page icon to the table.
=> more items per page options in table view

package.json, yarn.lock
I cannot tell that this is doing anything? There is zero information about this package at https://www.npmjs.com/package/vue-cli-plugin-eslint-config-vuetify
Note that `eslint-config-vuetify` is not a dependency since #692
=> Remove dev dependency `vue-cli-plugin-eslint-config-vuetify`

.browserslistrc
Turns out we weren't supporting Firefox ESR which is a major target for us, but we were targetting IE 10 & 11 which was probably bloating the transpiled code (due to excess pollyfills).
This gives us support for 90% of the market, excluding dead browsers (here's looking at you IE) and ensuring Firefox ESR is included (irrespective of its market share).
* Adds support for Firefox ESR (currently 102).
* Widens support for more browser versions.
* Removes support for IE (and other dead browsers).
=> browserlist: update browserlist

.eslintrc.js, .github/workflows/main.yml, cypress/component/viewToolbar.cy.js, cypress/support/component.js, src/components/cylc/ViewToolbar.vue, tests/e2e/specs/graph.cy.js, tests/e2e/specs/graphiql.cy.js, tests/e2e/specs/tree.cy.js
> Follow on from #1108 
> ~Built on #1108~
* Add component tests for the view toolbar.
* Enable component tests in CI.
=> View toolbar: tests

src/main.js, src/router/index.js
* Closes #1147.
* The token is used to set a secure cookie.
* We don't need it after that so we may as well remove it from the URL.
* This is cleaner and reduces the temptation for users to copy it with the URL.
=> router: strip the ?token when the app is first loaded

src/components/cylc/gscan/filters.js, tests/unit/components/cylc/gscan/utils.js
* Closes #1173
* Search by the whole workflow part of the ID (e.g. a/b/c) rather than just the "name" part (e.g. c).
=> gscan: fix searching for hierarchical workflows

CHANGES.md, src/components/cylc/workflow/Lumino.vue, tests/e2e/specs/workflow.cy.js
* Closes #1090
* When a new tab (i.e. Cylc view) is opened it should be acitvated (i.e. put on top).
=> workflow: open new tabs on top

src/components/cylc/TaskFilter.vue, src/components/cylc/common/filter.js, src/components/cylc/common/sort.js, src/components/cylc/table/Table.vue, src/components/cylc/tree/Tree.vue, tests/e2e/specs/table.cy.js, tests/e2e/specs/tree.cy.js, tests/unit/components/cylc/table/table.vue.spec.js, tests/unit/components/cylc/tree/tree.vue.spec.js
- The task filtering HTML and code was duplicated in the Tree and Table components. I have extracted it into its own component and simplified the code
- Closes #1118
=> Centralise task filtering into own component; list task states in logical order

.github/workflows/main.yml
Follow-up to #1140, it now has Firefox
=> GH Actions: use ubuntu-latest for e2e tests

CHANGES.md, src/components/cylc/table/Table.vue, src/utils/tasks.js, tests/e2e/specs/table.cy.js, tests/unit/utils/tasks.spec.js
These changes close #1180
In table view convert mean time from a number of seconds to an iso duration.
Question - do we want to make it mm:ss if duration < 3600?
=> show mean times as iso durations

package.json, yarn.lock
Alternative to #1192
Doesn't look like we are using this dev dependency directly.
=> deps: remove unnecessary babel-loader dev dep

src/utils/aotf.js
Fixes a small bug where the cutoff field is set in the broadcast form when opened from a task/family/cycle.
* Closes https://github.com/cylc/cylc-ui/issues/1222
* Note this solution is hardcoded in the UI and must stay that way until https://github.com/cylc/cylc-ui/issues/1225 is done.
=> aotf: prevent the "offset" field from being filled in

CHANGES.md, src/services/mock/json/App.json, src/store/workflows.module.js, tests/unit/store/workflows.spec.js
> Sibling https://github.com/cylc/cylc-flow/pull/5368
* Due to a bug in cylc-flow the ancestor order came out reversed more often than not.
* https://github.com/cylc/cylc-flow/pull/5368 fixes this bug.
* Now the ancestors should always come out the right way around so we need to reverse the iteration of this list.
=> store: fix ancestor order

src/components/cylc/Drawer.vue, src/components/cylc/Header.vue, src/components/cylc/gscan/GScan.vue, src/components/cylc/tree/TreeItem.vue, src/mixins/subscriptionView.js, src/styles/cylc/_dashboard.scss, src/styles/cylc/_drawer.scss, src/styles/cylc/_header.scss, src/views/Dashboard.vue, src/views/Guide.vue, src/views/NotFound.vue, src/views/UserProfile.vue, src/views/WorkflowsTable.vue, tests/unit/mixins/subscriptionView.spec.js
Remove stuff that is already deprecated as of Vue 2 / Vuetify 2
Vue:
- Deprecated slot syntax
Vuetify:
- Old grid/layout components
- `v-layout` -> `v-row` or `div`
- `v-flex` -> `v-col` or `div`
Vue-Router:
- Remove broken navigation guard that was not doing anything since first being added in #543
=> Remove deprecated Vue & Vuetify syntax

src/components/cylc/table/Table.vue, tests/e2e/specs/table.cy.js
A few trivial tweaks to tidy Table View column headings:
- `Job System --> Job Runner`
- (old terminology)
- `T-submit --> Submit` (etc.)
- (the "time" bit is obvious)
- `dT-mean --> <Run-Time>`
- (average or expected run time)
**Check List**
=> Minor tweaks to table header.

package.json
Follow-up to #1284, including a dummy commit to retrigger the 2nd stage of the release process now it's been fixed in #1286
=> Prepare release: 1.6.0 (again)

.github/workflows/auto_publish_release.yml, package.json
Follow-up to #1284 & #1287, cherry-picking https://github.com/cylc/cylc-ui/pull/1286 to fix the release stage 2 failure
=> Prepare release: 1.6.0 (3rd time's the charm)

.eslintrc.js, src/components/cylc/workflow/Lumino.vue, src/components/cylc/workflow/Toolbar.vue, src/views/Analysis.vue, src/views/Graph.vue, src/views/Log.vue, src/views/SimpleTree.vue, src/views/Table.vue, src/views/Tree.vue, src/views/Workspace.vue
In order to incorporate the dynamically imported SimpleTree view it seemed necessary to make all the views dynamically imported in Vue 3. Closes #1221.
I also took this opportunity to use [`<Teleport>`](https://vuejs.org/api/built-in-components.html#teleport) instead of the hacky solution for displaying these views in the Lumino tabs. (Hat tip to @kinow for the suggestion, it is rather nice!). Closes #1273.
Sync:
- #1139
**Check List**
=> Use dynamic async components for workspace view tabs + 1.6.x -> master (SimpleTree view)

src/utils/aotf.js
* Partially addresses #1364
* The `set-outputs` command is used reasonably often and current discussions could see its importance grow in the near future.
**Check List**
=> aotf: Make set-outputs a primary mutation for namespaces.

src/App.vue, tests/e2e/specs/userprofile.cy.js
Follow-up to #1305
Clicking the reset font size button in the user profile was not having an effect until you reloaded the page.
**Check List**
=> Fix font size reset bug

src/components/cylc/cylcObject/Menu.vue
Partially addresses #1364 
Make command menu items take up a bit less height so less mouse movement and less scrolling required.
<p float="left">
</p>
=> Make mutations menu more compact

CHANGES.md, src/components/cylc/table/Table.vue, src/graphql/queries.js, src/store/workflows.module.js, tests/unit/store/workflows.spec.js
Closes #1322.
Fixes a bug where tasks belonging to a family would sometimes disappear for a second only to reappear (typically when changing state), and would sometimes reappear permanently after having finished and moved out of the n=1 window.
There was an assumption the `childTasks` field of each updated-family delta always contained all current child tasks, but it only includes updated tasks (or maybe even arbitrary tasks?). Instead, use the pruned-task delta to remove the task from the family.
**Check List**
=> Fix family tasks discrepancy in tree view

src/main.js, tests/e2e/specs/url.cy.js
Closes #1147, re-do of #1151
After the browser has sent the token as part of the URL in the first GET (e.g. `https://localhost:1234/cylc/?token=ab1c234de`) the server responds with a cookie that is stored in the browser so the token is no longer needed.
I have not encountered the race condition described in #1153 but reviewers should test carefully
**Check List**
=> Strip token from URL when app is first loaded

renovate.json
I think these should be fine to automerge as the CI is extremely likely to fail if there's any issue
**Check List**
=> Renovate: automerge Vite dependencies

src/components/cylc/workflow/Lumino.vue, tests/e2e/specs/graphiql.cy.js
When navigating back from e.g. GraphiQL, there would be a duplicate but blank tree view tab in the workspace view. This was because `syncWidgets()` was being called twice for the same widget - once in the `created` lifecycle hook and once for the `_views` watcher.
Also fixed GraphiQL e2e test flakiness.
**Check List**
=> Fix duplicate blank tab bug

src/components/cylc/cylcObject/Menu.vue, src/utils/aotf.js, tests/e2e/specs/menu.cy.js
* Closes #1435
* Ensure the log mutation is listed, even when a user only has read permissions
* List the log mutation for workflows too.
The log mutation was getting filtered out when a user only had read permissions. The reason turned out to be this:
https://github.com/cylc/cylc-ui/commit/95f14f5fad6646fea683f3a11412125e069562f4#diff-ed0c1a902b9b47f63c1058d8ab66442fe9410209e762c70ddf15623b4b60dd1eR170
I expect this was a simple stopgap solution to hiding mutations for users who don't have write perms before we had the current solution implemented.
**Check List**
=> aotf: ensure log mutation is listed when appropriate

src/components/cylc/GraphNode.vue
Add a little extra vertical separation between the task name and cycle point to better allow for characters which extend below the baseline
**Check List**
=> GraphNode: nude the cycle point down a little

CHANGES.md, src/views/Graph.vue, src/views/Log.vue
Partial revert of 74670c0fff9ad1b52c583d0cc21c58a9de67a843
**Check List**
=> Fix toolbar toggle button color not changing

src/services/workflow.service.js
Closes https://github.com/cylc/cylc-ui/issues/1334
I don't have a good understanding of the issue on this one so I have just implemented the solution that was suggested on the [issue ](https://github.com/cylc/cylc-ui/issues/1334#issuecomment-1678971956)by @oliver-sanders .
This issue is hard to reproduce so its difficult to understand if this solution fixes the problem, but the tests still run locally at least.
**Check List**
=> Bug fix graphql 403

.github/workflows/main.yml
Workaround https://github.com/codecov/codecov-action/issues/837
- Reduces how hard we hit Codecov API
- Allows easy re-attempt to upload
- Fail CI check if coverage fails to upload
=> GH Actions: upload coverage to Codecov in separate job

CHANGES.md, src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/util.js, src/store/workflows.module.js
* Fixes an issue where a task might not have a firstParent.
* Closes #1470
* Fixes a traceback when opening the tree view.
* To replicate, close all views, open the simple tree view, wait for it to load, then open the tree view.
**Check List**
=> fix a couple of possible errors

src/components/cylc/Header.vue, src/composables/useLocalStorage.js, tests/e2e/specs/header.cy.js, tests/unit/composables/useLocalStorage.spec.js
Closes https://github.com/cylc/cylc-ui/issues/1457
- Added functionality for storing server owner and deployment in local storage.
- The state of the reactive array for deployments or owners is copied to a local storage variable each time it is changed.
- User can also remove values that have been stored.
- User cannot remove the initial values `onLoad` values.
**Check List**
=> Ability to store & remove server owner & deployment entries in dropdowns

src/router/index.js
We use [nprogress](https://www.npmjs.com/package/nprogress) to show a blue loading bar at the top of the viewport. (The progress of the loading bar is totally fake - it's just to relieve user impatience by showing that something is loading)
Here I've turned off the loading spinner icon that was showing in the top right corner, because it clashes with the user icon in the toolbar.
**Check List**
=> Turn off nprogress loading spinner

src/components/cylc/workflow/Toolbar.vue, src/model/User.model.js, src/services/user.service.js, tests/e2e/specs/toolbar.cy.js, tests/unit/model/user.model.spec.js
Closes https://github.com/cylc/cylc-ui/issues/1504
The userprofile endpoint has been extended in https://github.com/cylc/cylc-uiserver/pull/510 so it now provides user initials.
If for whatever reason the initials field is empty the avatar will be a user symbol
And if the initials field is populated the avatar will look like one of the two 
**Check List**
=> Fetch user initials from UIServer

package.json, yarn.lock
- https://github.com/vuejs/test-utils/issues/2257
**Check List**
=> Rollback `@vue/test-utils` to 2.4.1

src/components/cylc/gscan/WorkflowIcon.vue, src/model/WorkflowState.model.js, tests/unit/components/cylc/gscan/gscan.vue.spec.js, tests/unit/components/cylc/gscan/workflowicon.spec.js
Replaces / closes #1556
There is no 'error' state in cylc-flow: https://github.com/cylc/cylc-flow/blob/642ab8d22652f0aa3d5576d29736355a98b337d0/cylc/flow/workflow_status.py#L44-L58
**Check List**
=> Remove unused error state from workflow states

.github/workflows/auto_publish_release.yml, package.json
Release PR #1566 failed due to second stage using old node version
After this I will retrigger the release workflow
=> Revert version & fix GH Actions release workflow

src/store/workflows.module.js
* Reduce the overheads of `applyInheritance` for families with lots of children.
* Use a map for O(1) lookup times when checking whether child nodes are present in the store.
* This should change scaling from `O(nm)` to `O(m)` where `n` is the number of tasks in a family when created and `m` is the number of children after an update (n~=m for most cases).
* Partially addresses https://github.com/cylc/cylc-ui/issues/1614
* For the reduced example (`hours = 20`) this reduces the time taken by `applyInheritance` by ~85% from ~0.6s to <0.1s (though I'm sure these times will be subject to much jitter).
* Due to the non-linear scaling, I think this will make a larger difference to the full example.
Note, if you have no families in your workflow, then all tasks inherit from `root`.
Before: …
=> store: more efficient family tree building

src/store/workflows.module.js
* This was checking whether a node already exists in the tree before creating a new one.
* However, the `$index` already serves this function (nodes will be retrieved from the index if they already exist) so this check was redundant.
* This reduces the cost of the `createTreeNode` routine when the number of sibling elements is large.
Coverage suggests the `return` statement was never hit, logically, it shouldn't be possible (except, possibly in the event of traceback).
For the example in this issue https://github.com/cylc/cylc-ui/issues/1614 with `{% set hours = 20 %}` this reduces the cost of the `createTreeNode` routine by ~2/3.
The `some` operation should  be `O(n)`, but it gets called once for each of `n` items being added to the tree so it ends up `O(n^2)` which causes heavy load for …
=> data store: remove redundant safety check

.github/workflows/main.yml
This was preventing more than one job in the matrix from uploading screenshots on failure
=> GH Actions: fix screenshots artifact name clash

CHANGES.md, src/components/graphqlFormGenerator/EditRuntimeForm.vue
Work around https://github.com/vuetifyjs/vuetify/issues/19092
Closes #1610
**Check List**
=> Fix arrow keys not working in Edit Runtime form inputs

CHANGES.md, src/components/cylc/cylcObject/Menu.vue, src/components/cylc/workflow/Lumino.vue, src/components/cylc/workflow/Toolbar.vue, src/components/cylc/workflow/lumino-widget.js, src/mixins/subscriptionComponent.js, src/router/index.js, src/store/app.module.js, src/utils/index.js, src/views/UserProfile.vue, src/views/Workspace.vue, src/views/views.js, tests/e2e/specs/drawer.cy.js, tests/e2e/specs/workspace.cy.js, tests/unit/services/workflow.service.spec.js, tests/unit/store/app.spec.js, tests/unit/utils/index.spec.js
Closes #1278
Partially addresses #662
> 2. Save the layout last used by a workspace (important).
>     * When the user navigates away from a workflow, save the tab layout.
>     * When the user navigates back to the workflow, load the tab layout.
>     * When the user navigates to a new run of the same workflow, copy the layout from the last run of the workflow.
The layout is saved in the vuex store so only persists for the browser session. Ongoing investigation into saving it in local storage.
**Check List**
=> Save & restore workspace layout on navigation

package.json, renovate.json, src/graphql/index.js, yarn.lock
`subscriptions-transport-ws` uses [an exponential backoff function](https://github.com/apollographql/subscriptions-transport-ws/blob/36f3f6f780acc1a458b768db13fd39c65e5e6518/src/client.ts#L363) to cancel and retry the WebSocket connection when it first connects. The default initial timeout is 1s - https://github.com/apollographql/subscriptions-transport-ws/blob/master/src/defaults.ts#L1
I've increased it to 3s here to try and mitigate the slow initial connection problem #1200, though according to Oliver that problem may be caused by the connection closing unexpectedly (which triggers the WebSocket's `onclose`) rather than timing out (which doesn't). It's worth a shot anyway.
**Check List**
=> Increase initial WS timeout to try to mitigate slow connection problem

.mailmap, CHANGES.md, src/views/Tree.vue, tests/e2e/specs/tree.cy.js, tests/unit/views/tree.vue.spec.js
These changes build on the work undertaken to save & restore workspace layout on navigation https://github.com/cylc/cylc-ui/pull/1664
Which is part of a larger issue https://github.com/cylc/cylc-ui/issues/662
There is an equivalent pull request for the logview https://github.com/cylc/cylc-ui/pull/1688
**Check List**
=> TreeView: Use `initialOptions` prop to save view state

package.json, src/views/GraphiQL.vue, yarn.lock
- We use `preact` as a replacement for `react`
- Remove outdated and unused `preact-compat` dependency (the correct package is `preact/compat` which is included with `preact` (not to be confused with `@preact/compat` which is not needed either!))
**Check List**
=> Fix yarn warnings about `react`

.github/workflows/main.yml
We use timeouts on GH Actions to stop this sort of thing where something went wrong and it hung for a long time:
https://github.com/cylc/cylc-ui/actions/runs/8344029991/job/22835513719
=> GH Actions: add timeouts

src/utils/aotf.js
Ancillary to https://github.com/cylc/cylc-flow/pull/5658 - should not be merged until after that PR.
**Check List**
=> Added an icon for set

CHANGES.md, cypress/component/viewToolbar.cy.js, src/components/cylc/ViewToolbar.vue, src/components/cylc/log/Log.vue, src/services/mock/graphql.cjs, src/services/mock/json-server.cjs, src/services/mock/json/logData.cjs, src/services/mock/json/util.cjs, src/services/mock/websockets.cjs, src/utils/viewToolbar.js, src/views/Log.vue, tests/e2e/specs/log.cy.js, tests/unit/utils/viewToolbar.spec.js
Addresses numerous usability concerns raised by users:
- Close #1285 
- Close #1667
- Made the log display area scroll only, leaving the toolbar pinned to the top
- Moved the file list refresh button next to the file list dropdown
With word wrapping turned on:
=> Log view: wrap lines and improve UX

CHANGES.md, src/components/cylc/table/Table.vue, src/views/Table.vue, tests/e2e/specs/table.cy.js
I had a realisation about how to save the table view column sorting when navigating between workflows
Follow-up to #1711 
Partially addresses #662
**Check List**
=> Table view: remember sort & pagination state on navigation

.github/workflows/create_release_pr.yml, .github/workflows/main.yml, CHANGES.md, CONTRIBUTING.md, changes.d/1751.feat.md, changes.d/template.jinja, pyproject.toml
This will eliminate changelog conflicts
**Check List**
=> Switch to towncrier for changelog

changes.d/1755.feat.md, src/components/cylc/cylcObject/Menu.vue, src/components/cylc/workflow/Toolbar.vue, src/services/workflow.service.js, tests/unit/components/cylc/workflow/toolbar.vue.spec.js
* Closes #864
* Add a selector for switching the n-window extent between 0 & 3 inclusive.
* The n-window value appears to be preserved when navigating back to the workflow.
**Check List**
=> toolbar: add n-window-selector

renovate.json
Address warning in [dependency dashboard](https://github.com/cylc/cylc-ui/issues/1014):
Following advice from https://github.com/renovatebot/renovate/discussions/28753#discussioncomment-9276162
**Check List**
=> Renovate: address warning

changes.d/1717.feat.md, src/views/Graph.vue, tests/e2e/specs/graph.cy.js
These changes build on the work undertaken to save & restore workspace layout on navigation https://github.com/cylc/cylc-ui/pull/1664
Which is part of a larger issue https://github.com/cylc/cylc-ui/issues/662
There was an equivalent pull request for the log view https://github.com/cylc/cylc-ui/pull/1688
There is an equivalent pull request for the tree view which this builds on: https://github.com/cylc/cylc-ui/pull/1705
There is an equivalent pull request for the table view which this builds on: https://github.com/cylc/cylc-ui/pull/1711
**Check List**
=> Graph view: use `initialOptions` to save & restore view state on navigation

package.json, vite.config.js, yarn.lock
TIL the [`lodash`](https://www.npmjs.com/package/lodash) package is CommonJS and isn't tree-shaken!
This PR replaces `lodash` with [`lodash-es`](https://www.npmjs.com/package/lodash-es) which is an ES modules version of the package which allows tree-shaking.
I've confirmed this by comparing the non-minified built files before and after. There are a bunch of lodash functions included with the build on master that are not on this branch. The total reduction in the minified build is something like ~70kB
**Check List**
=> Switch to `lodash-es` for treeshaking

CONTRIBUTING.md, changes.d/1778.fix, src/graphql/graphiql.js, src/graphql/index.js, src/services/user.service.js, src/utils/urls.js
JupyterHub 4.1 applies XSRF checks consistently to authenticated GET requests, so apply the same `getCylcHeaders` logic in the graphQL POST request to all requests (userprofile was the only other one I found). As a result, the `getCylcHeaders` is moved to a common location in `utils/url`, rather than being confined to graphQL.
This solves the userprofile request, described in https://github.com/jupyterhub/jupyterhub/issues/4800
Together with https://github.com/cylc/cylc-uiserver/pull/592, cylc works with JupyterHub 4.1.5
**Check List**
=> Include XSRF token in userprofile request

package.json, src/components/cylc/workflow/Toolbar.vue, src/utils/index.js, tests/e2e/specs/toolbar.cy.js, tests/unit/utils/index.spec.js
Fixes an unreleased bug on master. Also adds some tests. Follow-up to #1755 
1. Start a workflow and use the UI to set the n-window to a value other than 1, e.g. 2
2. Stop the workflow
3. Navigate to the dashboard or a different workflow
4. Navigate back to the original workflow
5. You should see an error snackbar for a failed mutation
=> Fix N-window selector sending mutation upon navigation to stopped workflows

cypress/component/cylc-graph-node.cy.js, cypress/component/cylc-icons.cy.js, src/components/cylc/GraphNode.vue, src/components/cylc/SVGTask.vue, src/components/cylc/cylcObject/Menu.vue, src/styles/index.scss, src/views/Graph.vue
* There appears to have been a recent change in how multiple browsers measure the "bounding box" of SVG elements.
* This caused graph nodes to be measured much larger than the area they actually render to.
* This messed with the graph because we feed these dimensions into GraphViz when creating the virtual graph causing the nodes in the virtual graph to be given too much space. An error which is subsequently translated to the SVG graph.
* The changes in "bounding box" measurement appear to affect SVG Symbols and rotations.
* This commit removes the use of SVG symbols (and their related "use" elements) and moves the rotation from the circle element to a group.
* The use of SVG symbols made it easier for us to capture click events from behind the svgPanZoom layer.
* Removing SVG symbols …
=> graph: fix graph rendering

.github/workflows/main.yml
It's kind of useful to be able to see the rendered changelog.
https://docs.github.com/en/actions/using-workflows/workflow-commands-for-github-actions#adding-a-job-summary
To see it, you can go to the Actions summary page https://github.com/cylc/cylc-ui/actions/runs/9082240185#summary-24958150609
- https://github.com/cylc/release-actions/pull/72
=> GH Actions: print draft changelog job summary

changes.d/1466.feat.md, src/components/cylc/gantt/GanttChart.vue
Follow-up to #1466 
At present there isn't a great deal of use in the colour coding the gantt view by task name. I had a go at making it colour coded by cycle point, and added the job ID to the tooltip
**Check List**
=> Gantt view: colour code by cycle point

tests/unit/services/workflow.service.spec.js
This mocking did not seem to be working, resulting in noisy warnings when running the tests:
```
stdout | tests/unit/services/workflow.service.spec.js > WorkflowService > startSubscriptions > should start pending subscriptions
Subscription error: Failed to parse URL from /graphql ViewState { enumKey: 'ERROR', enumOrdinal: 2 } TypeError: Failed to parse URL from /graphql
at node:internal/deps/undici/undici:12502:13 {
[cause]: TypeError: Invalid URL: /graphql
at new URLImpl (C:\Users\ronnie.dutta\GitHub\cylc-ui\node_modules\whatwg-url\lib\URL-impl.js:23:13)
at Object.exports.setup (C:\Users\ronnie.dutta\GitHub\cylc-ui\node_modules\whatwg-url\lib\URL.js:54:12)
at new URL (C:\Users\ronnie.dutta\GitHub\cylc-ui\node_modules\whatwg-url\lib\URL.js:115:22)
at new Request …
```
=> Tests: fix mocking of apollo client

src/components/cylc/common/sort.js, src/components/cylc/table/Table.vue, src/components/cylc/table/sort.js, tests/e2e/specs/table.cy.js, tests/unit/components/cylc/common/sort.spec.js, tests/unit/components/cylc/table/sort.spec.js
Closes https://github.com/cylc/cylc-ui/issues/1255
When sorting by e.g. Submitted Time, an absence of a value means a job has not yet been submitted by the task that this row corresponds to. If sorting ascending, it is therefore logical that empty values should come last. But if sorting descending, you are probably interested in the newest jobs so again the empty values should come last. Note this is somewhat different behaviour to the linked issue.
**Check List**
=> Table view: sort empty entries last regardless of sort order

src/components/cylc/workspace/Widget.vue, tests/unit/components/cylc/gscan/gscan.vue.spec.js
Missed this out in #1802
Plus fix warning in test missed in #1794
**Check List**
=> Clean up event listener; fix warning in test

changes.d/1888.feat.md, src/components/cylc/commandMenu/Menu.vue, src/components/graphqlFormGenerator/components/MapItem.vue, src/utils/aotf.js
Closes #1874
For long env var names, they will be included in the hover tooltip so you can see them even if they are cut off in the text field.
**Check List**
=> Increase width of Edit Runtime dialog

pyproject.toml
Thanks to https://github.com/twisted/towncrier/pull/622, `towncrier build` will now fail on CI if anyone creates a changelog fragment with an invalid name.
**Check List**
=> Towncrier: enable checking of fragment names

changes.d/1979.fix.md, src/components/cylc/workspace/Toolbar.vue
* Closes #1845
* Disable the n-window selector if the authenticated user does not have the required permissions to run the setGraphWindowExtent mutation.
**Check List**
=> toolbar: disable n-window selector if appropriate

changes.d/1974.feat.md, src/components/cylc/TaskFilterSelect.vue, tests/e2e/specs/tree.cy.js
User request for a feature to make it easier to filter *out* task states.
**Check List**
=> task state filters: add select all action

changes.d/1982.feat.md, package.json, src/model/User.model.js, src/utils/icons.js, src/views/Dashboard.vue, src/views/UserProfile.vue, tests/e2e/specs/dashboard.cy.js, yarn.lock
Requires https://github.com/cylc/cylc-uiserver/pull/641
To review:
* Try running `cylc gui` and insepecting the Dashboard page (unless you have installed Jupyter lab) the link should be disabled.
* Try installing Jupyter Lab (`pip install jupyterlab`) and re-run the `cylc gui`, then follow the link on the Dashboard page.
**Check List**
=> jupyter lab dashboard link

src/components/cylc/Drawer.vue, src/views/Dashboard.vue
=> move GraphiQL from the draw to the dashboard

changes.d/1886.feat.md, cypress/component/info.cy.js, src/components/cylc/Info.vue, src/components/cylc/commandMenu/Menu.vue, src/services/mock/json/index.cjs, src/services/mock/json/infoView.json, src/utils/aotf.js, src/utils/outputs.js, src/views/Info.vue, src/views/UserProfile.vue, src/views/Workspace.vue, src/views/views.js, tests/e2e/specs/info.cy.js
Closes #1071
Closes #1896
* Bare bones task metadata view.
* Display task metadata, prerequisites and outputs.
* Display / functionality improvements and support for other information to follow in future PRs.
**Check List**
=> metadata view: introduce a minimal task metadata view

src/services/mock/json/userprofile.json, src/views/UserProfile.vue
This can be the case during development using an older UIS version.
Also added cylc extension to mock data.
Closes #2026
**Check List**
=> Handle possible lack of jupyter extensions field in userprofile

changes.d/2016.feat.md, cypress/component/treeItem.cy.js, src/components/cylc/commandMenu/Menu.vue, src/components/cylc/common/FlowNumsChip.vue, src/components/cylc/table/Table.vue, src/components/cylc/tree/TreeItem.vue, src/services/mock/checkpoint/get_checkpoint.py, src/services/mock/json/workflows/multi.json, src/services/mock/json/workflows/one.json, src/styles/cylc/_tree.scss, src/styles/index.scss, src/utils/index.js, src/utils/tasks.js, src/views/Graph.vue, src/views/Table.vue, src/views/Tree.vue, tests/e2e/specs/aotf.cy.js, tests/e2e/specs/graph.cy.js, tests/e2e/specs/table.cy.js, tests/e2e/specs/tree.cy.js, tests/unit/components/cylc/common/flowNumsChip.vue.spec.js, tests/unit/components/cylc/tree/tree.data.js, tests/unit/components/cylc/tree/tree.vue.spec.js, tests/unit/components/cylc/tree/treeitem.vue.spec.js, tests/unit/utils/index.spec.js, tests/unit/utils/tasks.spec.js
Partially addresses https://github.com/cylc/cylc-ui/issues/468
Flow numbers that are not 1 or None are now shown in the tree and table views. Tasks in flow=None are dimmed in the tree, table and graph views.
**Check List**
=> Show flow numbers

package.json, yarn.lock
<details>
<summary>vitest-dev/vitest (@&#8203;vitest/coverage-istanbul)</summary>
[Compare Source](https://redirect.github.com/vitest-dev/vitest/compare/v3.0.3...v3.0.4)
-   Filter projects eagerly during config resolution  -  by [@&#8203;sheremet-va](https://redirect.github.com/sheremet-va) and [@&#8203;AriPerkkio](https://redirect.github.com/AriPerkkio) in [https://github.com/vitest-dev/vitest/issues/7313](https://redirect.github.com/vitest-dev/vitest/issues/7313) [<samp>(dff44)</samp>](https://redirect.github.com/vitest-dev/vitest/commit/dff4406d)
-   Apply `development|production` condition on Vites 6 by [@&#8203;hi-ogawa](https://redirect.github.com/hi-ogawa) and [@&#8203;sheremet-va](https://redirect.github.com/sheremet-va) …
=> Update vitest to 3.0.4

src/services/mock/graphql.cjs
E.g. doing this named query without the `$id` arg:
```gql
query LogFiles {
logFiles (id: "foo") {
files
}
}
```
would crash the nodemon server. Now it returns the proper error
**Check List**
=> Mock server: catch errors in graphql execution

renovate.json
renovate suddenly decided to pin our Python version in GH Actions workflow: https://github.com/cylc/cylc-ui/pull/2097, which is not needed.
I think we can just rely on dependabot for GH Actions updates anyway.
**Check List**
=> Renovate: disable GH Actions updates as these are handled by dependabot

src/components/cylc/log/Log.vue, src/views/Log.vue, tests/component/specs/log.cy.js, tests/component/support/component-index.html, tests/unit/setup.js
Follow-up to #2017 
Fixes an issue where the scroll-to-top button needed clicking twice (Chromium).
**Check List**
=> Move all log autoscroll logic into component

src/components/cylc/analysis/TimeSeries.vue, src/views/Gantt.vue
* Respond to schema changes in https://github.com/cylc/cylc-uiserver/pull/657
* Jobs queries used to only return succeeded jobs (all the analysis view cares about).
* The `states` and `exstates` filters have now been implemented to allow jobs in other states to be queried (to support new views).
**Check List**
=> set state filter for offline job queries

src/App.vue, src/components/cylc/Mutation.vue, src/components/graphqlFormGenerator/EditRuntimeForm.vue, src/components/graphqlFormGenerator/FormInput.vue, src/components/graphqlFormGenerator/components/vuetify.js, src/plugins/vuetify.js
Closes https://github.com/cylc/cylc-ui/issues/1989
Workaround for https://github.com/vuetifyjs/vuetify/issues/18123
**Check List**
=> Fix reduced animation mode not working inside mutation form

changes.d/2135.feat.md, src/components/cylc/Drawer.vue, src/graphql/graphiql.js, src/graphql/index.js, src/router/index.js, src/services/mock/json-server.cjs, src/services/mock/json/version.json, src/services/plugin.js, src/services/user.service.js, src/store/user.module.js, src/utils/urls.js, tests/e2e/specs/drawer.cy.js, tests/unit/services/user.service.spec.js, tests/unit/store/user.spec.js, vite.config.js
Needs cylc-uis master (https://github.com/cylc/cylc-uiserver/pull/674)
In production mode, looks like this (where the main Cylc version == cylc-flow version):
N.B., while using this branch with cylc-uiserver 1.6.x checked out, the tooltip will show a bunch of raw HTML instead. This will not happen in production as the UI will be bundled with the cylc-uiserver 1.7.0.
**Check List**
=> Include cylc-flow & UIS version in sidebar

src/views/Graph.vue, tests/unit/views/graph-utils.js, tests/unit/views/graph.vue.spec.js
Follow-up to #1810
Partly addresses #1130
**Check List**
=> Graph grouping/collapsing code tidy

src/views/Dashboard.vue, src/views/Workflows.vue, src/views/WorkflowsTable.vue
* Add a version column to the workflow table (makes it easier for users to find workflows running under older versions as a stopgap measure).
* Rename the "workflows table" to "workflow table" (note the URL was already "workflow-table" so this is a non-change).
* Fix a problem where the "workflow-table" was not registering its subscription properly so was relying on the "workflows view" subscription for the data it needed.
* Removed fields from the "workflows view" subscription that are not needed for the workflows view.
**Check List**
=> workflows table: add cylc version column

src/views/Log.vue
If there is a failure to list the log files, the user should be presented with an error message, not left in the dark.
**Check List**
=> Log view: display any errors in listing the log files

src/views/Graph.vue, tests/unit/views/graph.vue.spec.js
Follow-up to https://github.com/cylc/cylc-ui/pull/1810
Partly addresses https://github.com/cylc/cylc-ui/issues/1130
It turns out we don't need the `descendants` field added in https://github.com/cylc/cylc-flow/pull/6610, and can actually simplify the `getTree` function
**Check List**
=> Graph grouping/collapsing: remove need for descendants field in query

src/utils/aotf.js
partially addresses https://github.com/cylc/cylc-uiserver/issues/333
Sibling to:
https://github.com/cylc/cylc-flow/pull/6478
https://github.com/cylc/cylc-uiserver/pull/672
Can be merged at any point.
This is a small/minor change to handle the JSON parsing of proper enums introduced with graphql-core v3.
**Check List**
=> backend graphql-core v3 adjustments

src/components/cylc/workspace/Lumino.vue, src/utils/reactivity.js, tests/unit/utils/reactivity.spec.js
Follow up to #2176 
I spotted that clicking the "reset layout" button caused two layout saves to occur instead of just one when it has finished resetting the layout.
**Check List**
=> Workspace layouts: avoid duplicate layout saving when resetting to default

.mailmap, CONTRIBUTING.md, src/components/cylc/tree/TreeItem.vue
Title:
Display Latest Job Platform on Unexpanded Task Node
Description:
- This pull request addresses issue #2153.
- Displays the latest job’s platform (e.g., [localhost]) next to collapsed task nodes in the Tree View.
- Mimics the behavior of the job summary icon — platform info disappears once the node is expanded.
- Uses the existing platform property for consistency with job nodes.
- Ensures UI alignment with the provided mockup.
Screenshot: 
Checklist:
=> Tree view platform badge

src/utils/aotf.js, tests/unit/utils/aotf.spec.js
As mentioned in https://github.com/cylc/cylc-flow/pull/6820, the reload command in the GUI currently will be broken for workflows running in Cylc < 8.5.0.
This is because https://github.com/cylc/cylc-flow/pull/6509 added a new argument in the schema. However we can work around this by not sending that arg when it is the default value.
This workaround can be removed when #1225 is addressed.
**Check List**
=> AOTF: Do not send non-required mutation args when they have the default value

src/views/Analysis.vue
#2181
This pull request address's issue raised in issue #2181.
It adds a simple closeable chip up by the filers that informs the user that the analysis tab only shows successful tasks
**Check List**
- [x ] I have read `CONTRIBUTING.md` and added my name as a Code Contributor.
=> Clarify Data View

changes.d/2078.feat.md, changes.d/2078.fix.md, src/components/cylc/ViewToolbar.vue, src/components/cylc/log/Log.vue, src/composables/localStorage.js, src/services/mock/json/logData.cjs, src/views/Log.vue, tests/component/specs/viewToolbar.cy.js, tests/e2e/specs/graph.cy.js, tests/e2e/specs/log.cy.js, tests/e2e/specs/userprofile.cy.js
Partially addresses #1809
The word wrap toggle button now sets the default for new log views.
Also fixes an issue where log word wrap was not breaking very long sequences of characters with no spaces.
**Check List**
=> Save log view word wrap default
