src/components/core/Alert.vue, src/layouts/Default.vue, src/model/Alert.model.js, src/router/index.js, src/services/suite.service.js, src/services/user.service.js, src/store/index.js, src/views/Suites.vue, src/views/UserProfile.vue, tests/unit/model/alert.spec.js, tests/unit/store/store.spec.js
Fix for issue #41. A simple alerts component.
=> Add alerts component

package-lock.json, package.json, src/plugins/axios.js, src/utils/graphql.js, src/views/UserProfile.vue, tests/unit/store/store.spec.js
Fix for #40 
Used [Vue.js loader](https://vuetifyjs.com/en/components/progress) to display progress, set the interceptors for Axios, then used `axios-fetch` as the fetch implementation for GraphQL 🎉
=> Add axios interceptors loading

README.md, docs/authentication/README.md, docs/authentication/jwt/package-lock.json, docs/authentication/jwt/package.json, package-lock.json, package.json, public/index.html, src/components/core/Drawer.vue, src/components/core/Footer.vue, src/views/About.vue, src/views/Dashboard.vue, src/views/Login.vue, src/views/NotFound.vue, src/views/Notifications.vue, src/views/Suite.vue, src/views/Suites.vue, src/views/UserProfile.vue
To complete the project rename.
=> Remove project name in files now

src/router/paths.js
=> Drop extra unused alias from dashboard

.nycrc, package-lock.json, package.json, src/components/index.js, src/model/Family.model.js, src/model/Task.model.js, src/services/mock/suite.service.js, src/services/suite.service.js, src/store/suites.module.js, src/transformers/vueadstabletree.transformer.js, src/views/Suite.vue, src/views/Suites.vue, tests/unit/model/family.model.spec.js, tests/unit/model/task.model.spec.js, tests/unit/services/suite.service.spec.js, tests/unit/store/suites.module.spec.js, tests/unit/transformers/vueadstabletree.transformer.spec.js
Using [vue-ads-table-tree](https://github.com/arnedesmedt/vue-ads-table-tree/), and displaying data from GraphQL query (need to use current WIP branch from David). Also works with offline mode for dev/testing.
=> Add first implementation of a suite tree view

src/components/cylc/Task.vue, src/views/Suite.vue
This PR adds props to the `Task` component, and also updates the current suite tree view to use this new component :+1:
=> Propize task component

src/components/cylc/WarningIcon.vue
addresses #116
Add a dismiss-able warning triangle like the one used in the current GScan.
=> component: warning icon

src/views/Graph.vue
hide tooltips on navigating away from the graph view and fix undo
=> hide tooltip on navigation and fix undo

src/views/Tree.vue
workflow id should be a list not a string.
=> workflow id to list

src/styles/cytoscape/cytoscape-custom.css, src/views/Graph.vue
This fixes a problem with displaying the graph when returning to the graph screen.
=> graph - debug reload

package.json
=> Reset version to 0.1

package-lock.json
@hjoliver forgot to include the change in the lock file for #175 . Just ran `npm install` so that it would update the file with the new version. Sorry, will try to remember it the next time.
=> Update version in package-lock.json too

src/components/cylc/TreeItem.vue, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, src/store/workflows.module.js, src/views/Tree.vue
=> Add leaf node

CHANGES.md
Complete 0.1, partial 0.2
One review should be enough. Will update my PR's if this gets merged first. Might need to ask others to do the same, or send follow-up PR's to amend the changelog later.
=> Add changes

.github/ISSUE_TEMPLATE/bug-report.md, .github/ISSUE_TEMPLATE/feature-request.md, .github/PULL_REQUEST_TEMPLATE.md
Copied from Cylc Flow. Didn't find anything that actually needed changes, no mentions of Cylc Flow repository directory. :+1:
=> Add GitHub templates

tests/unit/utils/tasks.spec.js
=> Add unit test for tasks.js

tests/unit/components/cylc/task.vue.spec.js
=> Add unit test for Task component

CHANGES.md, src/model/User.model.js, src/services/mock/user.service.mock.js, src/services/user.service.js, src/views/Dashboard.vue, src/views/UserProfile.vue, tests/unit/model/user.model.spec.js, tests/unit/services/user.service.spec.js
These changes close #258 
-  [x] No documentation update required.
=> Use data from JupyterHub to create the Hub URL (handling base_url)

CHANGES.md, vue.config.js
=> Transpile Vuetify so IE and Safari can use Cylc UI

CHANGES.md, src/components/core/Alert.vue
=> Remove container wrapper of alerts

src/components/core/Alert.vue
=> Use alert object only if not null

src/components/core/Footer.vue
=> Remove unused links from data section of Footer

src/views/NotFound.vue
=> Fix NotFound page using / for dashboard link instead of /dashboard

src/components/core/Footer.vue, src/styles/cylc/_footer.scss
=> Move footer styles to SCSS file

src/components/cylc/Job.vue, src/components/cylc/Task.vue, src/styles/cylc/_job.scss, src/styles/cylc/_task.scss, src/styles/index.scss, tests/unit/components/cylc/task.vue.spec.js, tests/unit/components/cylc/tree/treeitem.vue.spec.js
These changes partially address #222 
=> Make Job and Task functional components

CHANGES.md, src/components/cylc/Toolbar.vue, src/main.js, src/utils/graphql.js, src/views/Tree.vue, tests/unit/components/cylc/toolbar.vue.spec.js
=> Add mutations

CHANGES.md, src/main.js
=> Use wss when page protocol is https:

src/components/cylc/Graph.vue
Trivial; one review will do.
Continuing to reduce the amount of unnecessary cruft going to the console.
=> Graph View: remove some console debug calls.

.github/workflows/main.yml
=> Add lockfile lint

src/main.js, src/services/workflow.service.js, src/utils/graphql.js
These changes partially address #362 
=> Use a single WebSocket, and specify no-cache for the GraphQL links

src/router/paths.js
Tree view via `#/tree/workflow-name`
=> Make treeview available alone.

CHANGES.md, src/components/cylc/ConnectionStatus.vue, src/layouts/Default.vue, src/main.js, src/services/mock/workflow.service.mock.js, src/services/workflow.service.js, src/store/index.js, src/utils/graphql.js, tests/unit/components/cylc/connectionstatus.vue.spec.js, tests/unit/store/store.spec.js, tests/unit/utils/graphql.spec.js
These changes close #93 
Found one way to implement it while working on the websockets issue, so using the momentum to write docs and implement small changes such as this one.
=> Add ConnectionStatus component

CHANGES.md, src/components/cylc/TreeItem.vue, tests/unit/components/cylc/tree/tree.vue.spec.js
Especially when the user resizes the browser window, reducing the view port. Now
we are using CSS flex and setting nowrap where applicable.
These changes close #387 , and close #394 
=> Fix leaf and other tree nodes layout.

README.md, package-lock.json, package.json, src/plugins/index.js, src/plugins/veevalidate.js
=> Remove vee-validate

src/components/cylc/Drawer.vue
=> Show user name in the Drawer's Header component

src/views/Dashboard.vue
These changes close #407 
Set to milestone 0.2, but can be pushed to 0.3. I haven't added a changelog, but will do if necessary :+1: 
=> Set large modifier to same as medium/small for Dashboard elements

src/views/Dashboard.vue
=> Dashboard flex tweak.

src/components/material/Card.vue, src/styles/cylc/_header.scss
=> Fix WAVE issue on landing page due to low contrast for at-symbol

package.json, src/components/cylc/tree/TreeItem.vue, src/graphql/queries.js, src/services/mock/checkpoint.js, src/services/mock/generate
=> tree: restore the isHeld task status attribute

tests/unit/utils/graphql.spec.js
Just to test a few missing places in the `utils.graphql` module. Probably one review enough, given it's only adding a few unit tests.
=> More tests for utils.graphql

public/index.html, src/App.vue, src/main.js, src/store/index.js
=> Use base URL provided by Python backend (or mocked if offline) instead of building via JS

package.json
This way I'll stop forgetting to set the env then complain that offline mode is broken.
=> set environment for offline mode

src/components/cylc/Drawer.vue, src/components/cylc/graph/Graph.vue, src/plugins/axios.js, src/services/mock/generate, tests/e2e/specs/tree.js, tests/unit/components/graphqlFormGenerator/mutations.vue.spec.js
Just some typos, and removing unused code. I think one review should do, assuming CI runs fine.
=> Fix some typos, remove unused code, fix one shellcheck warning (IDE)

src/components/core/Alert.vue, src/main.js, tests/e2e/specs/alert.js, yarn.lock
=> Fix alert component colors

CHANGES.md, package.json, vue.config.js
=> Prepare 0.2 release

README.md
=> Add Anaconda badges

CHANGES.md, package.json, yarn.lock
These changes close #473 
Really impressed that going from 2.x to 3.x required simply no change at all :1st_place_medal: 
Tested with a running workflow, and found no issues. Confirmed in the browser console that WebSockets and GraphQL messages were being transferred correctly.
=> Update from apollo-client to @apollo/client

src/router/paths.js
=> Support any characters, including slashes, in workflow names

.nycrc, tests/unit/mixins/index.spec.js, tests/unit/mixins/toolbar.spec.js, tests/unit/mixins/treeview.spec.js
Just a few more tests to parts of the code that are not covered yet.
=> Add more tests for mixins, and exclude the graphiql module (needs a backend)

src/components/cylc/tree/Tree.vue, tests/unit/components/cylc/tree/tree.vue.spec.js
=> Use the correct node ID when removing the tree item from the cache

src/components/cylc/tree/Tree.vue
These changes close #508 
No changelog as this is fixing a feature that was not released yet. Also no tests, this is only altering the layout (although it could break e2e tests, but no changes in the code/behavior).
=> Use vuetify 2.x grid classes, support responsive layout too

CHANGES.md, CONTRIBUTING.md, src/components/cylc/tree/Tree.vue, tests/e2e/specs/tree.js
These changes close #513 
Evidence of the changes
The limit is 4 but is hardcoded in the Tree.vue, so if you are planning to have this number as a limit in a config file, let me know if you already have one to place it there.
=> Improve v-select of task state filter in responsive

src/model/TaskState.model.js, src/utils/tasks.js
These changes close #516 
One review should be enough.
=> Remove runahead state

.github/workflows/main.yml
=> Update cypress-action from v1 to v2

src/components/cylc/tree/cylc-tree.js
=> Allow nodes without parents in GraphQL deltas payload data

src/components/cylc/tree/cylc-tree.js
One review should do. Noticed this file was missing the header while working on #504 
=> Add missing license header

src/components/cylc/gscan/GScan.vue, src/styles/cylc/_gscan.scss, src/views/Dashboard.vue, tests/unit/components/cylc/gscan/gscan.vue.spec.js
=> Use skeleton loaders in the Cylc UI landing page

src/styles/cylc/_task.scss
=> task: vertically centre icons

src/components/cylc/workflow/lumino-widget.js, src/graphql/queries.js, src/model/WorkflowState.model.js, src/utils/aotf.js
=> Fix typos and jsdocs tags

.github/workflows/update_copyright.yml, CONTRIBUTING.md, README.md
=> Auto update copyright year

.github/workflows/update_copyright.yml
=> GH Actions: prevent update_copyright workflow from running on forks

src/components/cylc/Task.vue, src/components/cylc/gscan/index.js, src/model/TaskState.model.js, src/services/mock/checkpoint.js, src/styles/cylc/_task.scss, src/utils/tasks.js
UI counterpart of https://github.com/cylc/cylc-flow/pull/4014
=> Rename "ready" task state to "preparing".

src/components/cylc/gscan/GScan.vue, src/components/cylc/gscan/WorkflowIcon.vue, tests/unit/components/cylc/gscan/workflowicon.spec.js
=> Add WorkflowIcon component (for GScan)

.github/workflows/main.yml
These changes partially address #590
=> Disable macos build for now

package.json, vue.config.js, yarn.lock
=> Run circular-dependencies plugin during build

.github/workflows/update_copyright.yml, src/services/mock/generate, src/services/mock/one/flow.cylc, src/views/Dashboard.vue
UI sibling of https://github.com/cylc/cylc-flow/pull/4174
=> Terminology: suite to workflow.

src/views/Dashboard.vue, src/views/Guide.vue
* Fix dashboard links after the docs move (note using latest for now)
* Point the quickstart button at the "guide" page.
* Fix the guide page to vuetify changes.
=> Docs and guide

src/components/cylc/tree/cylc-tree.js, tests/unit/components/cylc/tree/tree.spec.js
=> Fix jobs order (newest first)

CHANGES.md, src/components/cylc/Job.vue, src/components/cylc/tree/TreeItem.vue, src/styles/cylc/_job.scss, tests/unit/components/cylc/job.vue.spec.js
These changes partially address #333 
=> Display multiple jobs with a shadow under the icon

CHANGES.md, src/styles/cylc/_dashboard.scss, src/views/Dashboard.vue
=> Avoid content shift by using a skeleton loader in each cell with the item-count

CHANGES.md, src/components/cylc/Task.vue, src/components/cylc/tree/TreeItem.vue, src/graphql/queries.js, src/services/mock/checkpoint.js, src/services/mock/checkpoint/get_checkpoint.py, src/styles/cylc/_task.scss, src/views/Guide.vue, tests/unit/components/cylc/task.vue.spec.js
cylc-ui sibling of https://github.com/cylc/cylc-flow/pull/4103 (merge the cylc-flow PR first)
=> Add is_runahead task indicator.

src/utils/urls.js, src/views/Dashboard.vue, tests/unit/utils/urls.spec.js
#677 broke the Dashboard's Hub URL, which isn't supposed to have the user bit in it.
Not sure if this is the best way to fix it?
=> Fix dashboard hub URL.

src/model/WorkflowState.model.js
Adding the new test that was missing in the workflow states enum. Extracted the change from the GScan pull request #543 
=> Add the installed workflow state

CHANGES.md
As promised in the comments of #543 , updated the issues assignee and milestone, and also updated the changelog to include missing issues for 0.5.0 :+1: 
One review should be enough.
=> Update changelog after #543

src/components/cylc/workflow/Toolbar.vue, src/views/Mutations.vue, src/views/Tree.vue, src/views/Workflow.vue, src/views/WorkflowsTable.vue
These changes partially address #376
Coverage change result of code that was removed, reducing the total coverage. But the new code appears to be covered/exercised by e2e and unit tests - https://app.codecov.io/gh/cylc/cylc-ui/compare/699
=> Simplify how we add views to the Workflow view as widgets

src/components/cylc/gscan/GScan.vue, src/model/TaskState.model.js, src/model/WorkflowState.model.js, tests/unit/components/cylc/gscan/gscan.vue.spec.js
=> Fix sorting in GScan due to strange enumify behaviour

src/components/cylc/WarningIcon.vue, src/components/cylc/cylcObject/Menu.vue, src/styles/cylc/_aotf.scss, src/styles/cylc/_drawer.scss, src/styles/cylc/_header.scss, src/styles/cylc/_toolbar.scss, src/utils/aotf.js
Hadn't reviewed UI's code with the IDE in a while. Found a few issues, fixing here with no associated issue.
=> Small improvements

.github/workflows/create_release_pr.yml, .github/workflows/shortlog.yml, .mailmap, CONTRIBUTING.md
=> Check contributing with GH actions

src/styles/cylc/_task.scss
These changes partially address #701 
Edit - this really only answers the first bullet point of the ticket, and may be more than a "tick or two". 
The main outcome from my point of view is that I've had a play with Vue and got my hands dirty.
N.B. I was thinking about what it might look like to the visually impaired, and was pleased with the results of pressing ctrl+ multiple times.
=> start progress 'clock' at ~20% to differentiate submitted from running.

src/services/mock/json/IntrospectionQuery.json, src/utils/aotf.js
These changes partially address https://github.com/cylc/cylc-uiserver/issues/242. Sibling to https://github.com/cylc/cylc-flow/pull/4481 (see for more details), and https://github.com/cylc/cylc-uiserver/pull/270
=> Remove ping from the UI

.github/workflows/create_release_pr.yml
Fixes a minor issue with the release stage one where the checkout is happening *after* the contributor list is checked.
=> actions: fix release stage one

.github/workflows/create_release_pr.yml
=> actions: fix release stage one (again)

.github/workflows/auto_publish_release.yml, .github/workflows/create_release_pr.yml
- Fix broken link to release at the "comment on PR" step after publishing
- Include tests workflow status badge in release PR body
- Tidy
=> GH Actions: update release workflows

src/components/graphqlFormGenerator/components/vuetify.js
Response to: https://github.com/cylc/cylc-ui/pull/876#pullrequestreview-850642656
=> uid: update form placeholders

src/components/cylc/Toolbar.vue, src/components/cylc/workflow/Toolbar.vue
=> made mobile burger button dark, hence actually visible

src/views/Table.vue, src/views/Tree.vue
=> Fixed mutations menu showing up more then once

CHANGES.md, package.json
Reverts cylc/cylc-ui#929
Attempt 2
=> Revert "Prepare release: 1.0.0"

package.json, yarn.lock
Replaces:
- #907 
- #910 
- #921 
- #925 
=> Consolidate dependabot changes

CHANGES.md, src/components/cylc/cylcObject/plugin.js, src/components/cylc/gscan/GScan.vue, src/components/cylc/gscan/WorkflowIcon.vue, src/components/cylc/tree/TreeItem.vue, src/layouts/Default.vue, src/styles/cylc/_gscan.scss, src/views/Workflow.vue, tests/e2e/specs/gscan.js, tests/e2e/specs/menu.js
These changes close #867 
Massive thanks to @MetRonnie for helping me get my head around this one.
=> Add mutations to Gscan workflow icons.

src/graphql/queries.js, src/services/mock/json/IntrospectionQuery.json
These changes partially address https://github.com/cylc/cylc-uiserver/issues/341
Sibling to https://github.com/cylc/cylc-flow/pull/4791
(Can go in before sibling, UI master will be broken with sibling merged first)
=> remove ghosts from graphql args

.github/workflows/shortlog.yml, .mailmap
Fix `.mailmap`
Before:
```console
$git shortlog -se
25  Aaron Cole <aaron@epiphron.co.nz>
2  Alex Szabó <kreatemore@gmail.com>
2  Ash Newport <anewport@dxc.com>
1347  Bruno Kinoshita <kinow@users.noreply.github.com>
1  Carol Barno <32536886+CarolBarno@users.noreply.github.com>
1  David Sutherland <davidwollow@gmail.com>
4  Edgardo Ramírez <soldiercrp@gmail.com>
1  Garrett Walker <garbwalk@ut.utm.edu>
4  Giuliano Serrao <giulianoserrao@gmail.com>
235  Hilary Oliver <h.oliver@niwa.co.nz>
13  Martin Ryan <MartinRyan@users.noreply.github.com>
11  Matt Shin <matthew.shin@metoffice.gov.uk>
28  Mel Hall <37735232+datamel@users.noreply.github.com>
230  Oliver Sanders <oliver.sanders@metoffice.gov.uk>
54  Ronnie Dutta …
```
=> Fix .mailmap

tests/unit/components/cylc/gscan/gscan.vue.spec.js
Add test for #931 
Replaces #936 since that test does not fail for https://github.com/cylc/cylc-ui/commit/8dd7e52b9d9bc1d7ac355952a4f1baae54f511d7 which was the last commit before #931
=> Test hierarchical gscan

yarn.lock
We get messages about updating the browser list, should probably do that:
```
npx browserslist@latest --update-db
```
=> caniuselite

src/components/cylc/tree/TreeItem.vue, src/components/cylc/tree/nodes.js
=> Change 'batch sys' to 'job runner'.

src/utils/aotf.js
* Add icon for the clean mutation.
* Add the clean mutation to the default list.
=> aotf: add icon for the clean mutation

yarn.lock
* Closes https://github.com/cylc/cylc-ui/security/dependabot/47
* Move to patched versions of terser.
=> deps: bump terser

package.json, yarn.lock
These are included with @babel/preset-env
=> Trim unnecessary direct dependencies on babel proposals

src/views/Guide.vue
- document task and job states better
- remove the ugly `v-card` drop-shadow (we don't have other 3D design elements).
=> Update the Quick Start guide a bit.

.github/workflows/main.yml
=> GH Actions: bump cypress-io/github-action to v4

src/components/cylc/table/Table.vue, src/components/cylc/table/deltas.js, src/components/cylc/tree/TreeItem.vue, tests/unit/components/cylc/table/deltas.spec.js
These changes close #1066 and #1099
Hi! I saw some activity in Cylc UI today, went through the tickets now before dinner, and found one that looked simple. Took me longer to actually remember about the code base than to find where the bug (possibly) was :smile: 
I think the deltas for tables is always using the same element, if we get the element with highest `submitNum` first (which happens in the mock/offline table deltas [see JSON in service/mock folder]). Didn't have time to do a more through investigation and write tests, but figured you guys would be able to take over and confirm if it's indeed a bug and maybe use this as reference for a fix (feel free to discard this PR :+1: )
:vulcan_salute:
=> Quick commit to test the table deltas

package.json, yarn.lock
Attempt to fix CI failures - https://github.com/cypress-io/cypress/issues/24195
=> Bump cypress to v10.10.0

.eslintrc.js, src/views/Dashboard.vue
=> Dashboard documentation links open in new tab

yarn.lock
Do that thing we keep getting pestered to do.
=> update: caniuse-lite

src/store/workflows.module.js
=> store: remove log and correct typo

CHANGES.md, src/components/cylc/cylcObject/Menu.vue
=> fix for jumping of expanded mutations menu.

src/views/Dashboard.vue, src/views/WorkflowsTable.vue, src/views/Workspace.vue, tests/e2e/specs/dashboard.cy.js, tests/e2e/specs/workflowsTable.cy.js, tests/e2e/specs/workspace.cy.js
Follow-up to #1183 
- Fix broken route
- Add some e2e tests for Workflows-Table view and broken link tests for Dashboard
=> Fix broken link

yarn.lock
Closes https://github.com/cylc/cylc-ui/security/dependabot/55
Closes https://github.com/cylc/cylc-ui/security/dependabot/57
Closes https://github.com/cylc/cylc-ui/security/dependabot/58
Closes https://github.com/cylc/cylc-ui/security/dependabot/59
Closes https://github.com/cylc/cylc-ui/security/dependabot/60
=> deps: bump loader-utils

yarn.lock
Closes https://github.com/cylc/cylc-ui/security/dependabot/67
=> deps: bump http-cache-semantics

yarn.lock
Closes https://github.com/cylc/cylc-ui/security/dependabot/64
Addresses https://github.com/cylc/cylc-ui/security/dependabot/65
=> deps: json5

.github/workflows/auto_publish_release.yml
See https://github.com/cylc/release-actions/pull/45
=> Replace actions/create-release with our version

.gitignore, CHANGES.md, cypress/component/cylc-graph-node.cy.js, package.json, src/components/cylc/GraphNode.vue, src/components/cylc/cylcObject/Menu.vue, src/components/cylc/log/Log.vue, src/graphql/queries.js, src/mixins/subscriptionComponent.js, src/router/paths.js, src/services/mock/json/index.js, src/services/mock/json/logData.json, src/services/mock/json/logFiles.json, src/services/workflow.service.js, src/styles/cylc/_job.scss, src/utils/aotf.js, src/utils/uid.js, src/views/Graph.vue, src/views/Log.vue, tests/e2e/specs/log.cy.js, yarn.lock
> **Built Atop:** https://github.com/cylc/cylc-ui/tree/log-tidy
> **Siblings:** https://github.com/cylc/cylc-uiserver/pull/439 & https://github.com/cylc/cylc-flow/pull/5453
> **Supersedes:** #1268 (PR got broke)
Closes #1206
Closes #1251
* Log files:
* List available log files:
* Support viewing other workflow log files e.g. `config/` and `install/`.
* Support viewing logs from previous job submissions.
* Viewing:
* Support stripping timestamps from logs.
* Add a workflow/job toggle to switch between workflow and job logs.
* Remove the search/update button by subscribing reactively.
* Add a button for refreshing the log file list.
* Disable the log file input when the file list is loading.
* Display the path to the log file being viewed.
* Display the connection status of the subscription …
=> log: various goodies

src/views/Graph.vue
Small follow-up to #1269
**Check List**
=> Graph view: prevent possibilty of race condition on layout

package.json, yarn.lock
Not sure why Renovate hasn't picked this one up?
=> Update vite & cypress

.mailmap, CHANGES.md, package.json, src/components/cylc/table/Table.vue, tests/e2e/specs/table.cy.js
Includes:
- #1266
Please do a **normal merge**, not squash
=> 1.6.x -> master (final)

CHANGES.md, src/components/cylc/table/Table.vue, src/store/workflows.module.js, src/utils/tasks.js, src/views/Table.vue, tests/unit/components/cylc/table/table.vue.spec.js, tests/unit/components/cylc/tree/tree.vue.spec.js, tests/unit/components/cylc/tree/treeitem.vue.spec.js, tests/unit/utils/tasks.spec.js, tests/unit/views/table.vue.spec.js
Closes #1292 
The first job was being shown for a row. This PR fixes it to show the latest job.
**Check List**
=> Fix incorrect latest job in table view

CHANGES.md, cypress/support/component.js, src/App.vue, src/components/cylc/cylcObject/Menu.vue, src/main.js, src/mixins/appSettings.js, src/plugins/vuetify.js, src/store/app.module.js, src/store/options.js, src/store/user.module.js, src/store/workflows.module.js, src/views/UserProfile.vue, tests/.eslintrc.js, tests/e2e/specs/userprofile.cy.js, tests/unit/components/app.vue.spec.js, tests/unit/utils/graphql.spec.js
The main benefit to this other than for accessibility concerns is reduced latency on virtual desktops.
This PR also improves the mutation menu appearance after #1269
**Check List**
=> Add user setting to turn off most animations

package.json, yarn.lock
=> Remove unused dependency on utf-8-validate

CHANGES.md, src/views/UserProfile.vue, src/views/Workspace.vue, tests/e2e/specs/userprofile.cy.js
Built upon / supersedes @AaronDCole's #1263, rebased onto master.
Closes #1036
**Check List**
=> Provide a setting for changing the default view

renovate.json
This should speed up automerges
https://docs.renovatebot.com/configuration-options/#platformautomerge
Also added yarn updates to the list of automergeable updates
=> Renovate: use GitHub native automerge

cypress.config.js, cypress/support/component.js, package.json, renovate.json
=> Renovate schedule & Cypress component coverage

src/components/Markdown.vue, src/components/cylc/ConnectionStatus.vue, src/components/cylc/Drawer.vue, src/components/cylc/TaskFilter.vue, src/components/cylc/Toolbar.vue, src/components/cylc/cylcObject/Menu.vue, src/components/cylc/gscan/GScan.vue, src/components/cylc/table/Table.vue, src/components/cylc/tree/Tree.vue, src/components/cylc/tree/TreeItem.vue, src/components/cylc/workflow/Toolbar.vue, src/components/graphqlFormGenerator/FormGenerator.vue, src/components/graphqlFormGenerator/components/List.vue, src/views/Analysis.vue, src/views/Dashboard.vue, src/views/Graph.vue, src/views/Log.vue, src/views/UserProfile.vue, src/views/WorkflowsTable.vue
Closes #1247
Can't say I've noticed any change in performance however. Can bump this to later milestone.
**Check List**
=> Fix unnecessary reactive data

yarn.lock
Bump semver version.
Closes https://github.com/cylc/cylc-ui/security/dependabot/81
=> deps: semver

src/services/mock/json/IntrospectionQuery.json
* See https://github.com/cylc/cylc-flow/issues/5610
**Check List**
=> extra log files: remove legacy

README.md, src/components/README.md, src/layouts/README.md, src/mixins/README.md, src/store/README.md, src/views/README.md
Add some docs to explain how data is requested/provisioned.
Add some small readme's to explain different aspects of the project structure.
**Check List**
=> add some developer documentation

CHANGES.md, CONTRIBUTING.md, src/components/cylc/Mutation.vue, tests/e2e/specs/mutation.cy.js
Closes #835
Added additional sub-components to v-card component including v-card-title and v-card-text.
Added styling to v-card-text to make it 50% of view port height and have scroll in y direction.
Added Mark Dawson to contributing.md
**Check List**
=> Feature mutation form sticky buttons

src/components/cylc/Header.vue, src/components/cylc/workflow/Toolbar.vue, tests/e2e/specs/header.cy.js
=> Review suggestions for multi user functionality

src/components/cylc/GraphNode.vue
=> Graph node: nudge the task icons down

renovate.json, tests/e2e/specs/dashboard.cy.js, tests/e2e/specs/userprofile.cy.js, tests/e2e/specs/workspace.cy.js
- Never had a problem with Vue updates
- Added tests should ensure both `@unhead/vue` and `vue-i18n` are working
**Check List**
=> Renovate: automerge more dependencies

src/model/Alert.model.js, src/router/index.js, src/store/options.js, src/utils/aotf.js, tests/e2e/specs/alert.cy.js, tests/unit/model/alert.model.spec.js
This is to allow debugging of stack trace
**Check List**
=> Error handling: always log original error object if possible

src/components/graphqlFormGenerator/EditRuntimeForm.vue
Follow-up to https://github.com/cylc/cylc-ui/pull/1656#discussion_r1500664814
**Check List**
=> Remove no-longer-needed Vuetify workaround

CHANGES.md, src/components/cylc/table/Table.vue, src/views/Table.vue, src/views/Tree.vue, tests/e2e/specs/table.cy.js, tests/unit/components/cylc/table/table.vue.spec.js, tests/unit/views/table.vue.spec.js
=> TableView: Use initialOptions prop to save view state (cherry-pick #1711)

CHANGES.md, package.json
=> 2.4.x -> master

changes.d/1510.feat.md
=> Add missed changelog entry

changes.d/1780.fix.md
=> Add missing changelog entry

src/components/cylc/gantt/GanttChart.vue, tests/unit/components/cylc/analysis/analysistimeseries.vue.spec.js, tests/unit/components/cylc/gantt/ganttChart.vue.spec.js, tests/unit/components/cylc/workflow/toolbar.vue.spec.js
=> Address warnings emitted during unit tests & tidy

src/views/NoAuth.vue, src/views/NotFound.vue
Fixes the 404 page which got a bit ugly, possibly during the Vue 3 upgrade.
Uses newish [`VEmptyState`](https://vuetifyjs.com/en/components/empty-states/#usage) component for ease, and applied the same to the no-auth page.
**Check List**
=> Fix janky 404 page

src/components/cylc/analysis/BoxPlot.vue, src/components/cylc/analysis/TimeSeries.vue, src/components/cylc/gantt/GanttChart.vue
Fix issue raised in https://github.com/cylc/cylc-ui/issues/1944
**Check List**
=> Explicitly defining toolbar items.

renovate.json
=> Renovate: fix config for sass

src/components/cylc/commandMenu/Menu.vue, src/components/cylc/workspace/Toolbar.vue, src/services/mock/json/workflows/multi.json, src/services/mock/json/workflows/one.json
Follow-up to #2171
**Check List**
=> Add workflow Cylc version to toolbar and menu

src/views/Graph.vue
=> Graph view: Fix missing edge between collapsed cycles that contain collapsed families

.github/workflows/shortlog.yml
Mirror https://github.com/metomi/rose/pull/2911
=> Run shortlog weekly
